// Central translation catalog for shared interface text.
// Generated business content intentionally remains untranslated for now.
export const supportedLanguages = {
  en: { label: 'English', direction: 'ltr' },
  he: { label: 'עברית', direction: 'rtl' },
  ar: { label: 'العربية', direction: 'rtl' },
  ru: { label: 'Русский', direction: 'ltr' },
}

export const translations = {
  en: { findLeads: 'Find Leads', loadDemoLeads: 'Load Demo Leads', exportCsv: 'Export CSV', saveToGoogleSheets: 'Save to Google Sheets', proposal: 'Proposal', demoSite: 'Demo Site', salesPitch: 'Sales Pitch', whatsapp: 'WhatsApp', close: 'Close', language: 'Language', crm: 'CRM', crmStatus: 'Status', crmNotes: 'Notes', crmNotesPlaceholder: 'Add notes…', crmNextFollowUp: 'Next Follow-up', statusNew: 'New', statusContacted: 'Contacted', statusWhatsappSent: 'WhatsApp Sent', statusProposalSent: 'Proposal Sent', statusNegotiation: 'Negotiation', statusWon: 'Won', statusLost: 'Lost', dashboard: 'Dashboard', bsHunter: 'BS Hunter', tasks: 'Tasks', websites: 'Websites', settings: 'Settings', totalLeads: 'Total Leads', hotLeads: 'Hot Leads', demoSites: 'Demo Sites', proposals: 'Proposals', followUps: 'Follow-ups', wonDeals: 'Won Deals', nextPriorityAction: 'Next Priority Action', businessOverview: 'Business overview', dashboardSubtitle: 'Your leads, pipeline, and next move in one place.', followUpWith: 'Follow up with', findFirstLeads: 'Build your first lead list', priorityLeadMessage: 'Review this lead, prepare the demo, and move the conversation forward.', emptyDashboardMessage: 'Open BS Hunter to discover businesses and start building your pipeline.', openBsHunter: 'Open BS Hunter', crmPlaceholder: 'Your full CRM dashboard will appear here in a future update.', tasksPlaceholder: 'Task planning and daily workflows are coming next.', websitesPlaceholder: 'Generated and published websites will be managed here.', settingsPlaceholder: 'Business OS preferences and integrations will be managed here.', priorityReason: 'Reason', recommendedAction: 'Recommended action', priorityOverdueReason: 'A scheduled follow-up is overdue.', priorityTodayReason: 'A follow-up is scheduled for today.', priorityHotNewReason: 'This new lead has a score of 80 or higher.', priorityContactedReason: 'This lead was contacted and is ready for the next step.', priorityFollowUpAction: 'Contact the business and record the outcome.', priorityContactAction: 'Make the first contact while the opportunity is strong.', priorityPrepareAction: 'Prepare a demo or proposal and continue the conversation.', priorityNoLeadReason: 'No lead currently requires immediate attention.', priorityOpenHunterAction: 'Open BS Hunter and load or find leads.' },
  he: { findLeads: 'חיפוש לידים', loadDemoLeads: 'טעינת לידים לדוגמה', exportCsv: 'ייצוא CSV', saveToGoogleSheets: 'שמירה ב-Google Sheets', proposal: 'הצעת מחיר', demoSite: 'אתר לדוגמה', salesPitch: 'תסריט מכירה', whatsapp: 'WhatsApp', close: 'סגירה', language: 'שפה', crm: 'CRM', crmStatus: 'סטטוס', crmNotes: 'הערות', crmNotesPlaceholder: 'הוספת הערות…', crmNextFollowUp: 'מעקב הבא', statusNew: 'חדש', statusContacted: 'נוצר קשר', statusWhatsappSent: 'נשלח WhatsApp', statusProposalSent: 'נשלחה הצעה', statusNegotiation: 'משא ומתן', statusWon: 'נסגר', statusLost: 'אבד', dashboard: 'לוח בקרה', bsHunter: 'BS Hunter', tasks: 'משימות', websites: 'אתרים', settings: 'הגדרות', totalLeads: 'סה״כ לידים', hotLeads: 'לידים חמים', demoSites: 'אתרי דמו', proposals: 'הצעות', followUps: 'מעקבים', wonDeals: 'עסקאות שנסגרו', nextPriorityAction: 'הפעולה הבאה בעדיפות', businessOverview: 'סקירת העסק', dashboardSubtitle: 'הלידים, התהליך והצעד הבא במקום אחד.', followUpWith: 'יצירת קשר עם', findFirstLeads: 'בניית רשימת הלידים הראשונה', priorityLeadMessage: 'בדקו את הליד, הכינו דמו וקידמו את השיחה.', emptyDashboardMessage: 'פתחו את BS Hunter כדי למצוא עסקים ולהתחיל לבנות תהליך מכירה.', openBsHunter: 'פתיחת BS Hunter', crmPlaceholder: 'לוח ה-CRM המלא יופיע כאן בעדכון עתידי.', tasksPlaceholder: 'ניהול משימות ותהליכי עבודה יגיע בקרוב.', websitesPlaceholder: 'כאן ינוהלו אתרים שנוצרו ופורסמו.', settingsPlaceholder: 'כאן ינוהלו העדפות ואינטגרציות של Business OS.', priorityReason: 'סיבה', recommendedAction: 'פעולה מומלצת', priorityOverdueReason: 'מועד המעקב שנקבע כבר עבר.', priorityTodayReason: 'נקבע מעקב להיום.', priorityHotNewReason: 'זהו ליד חדש עם ציון 80 ומעלה.', priorityContactedReason: 'נוצר קשר עם הליד והוא מוכן לשלב הבא.', priorityFollowUpAction: 'צרו קשר עם העסק ותעדו את התוצאה.', priorityContactAction: 'צרו קשר ראשון כל עוד ההזדמנות חזקה.', priorityPrepareAction: 'הכינו דמו או הצעה והמשיכו את השיחה.', priorityNoLeadReason: 'אין כרגע ליד הדורש טיפול מיידי.', priorityOpenHunterAction: 'פתחו את BS Hunter וטענו או חפשו לידים.' },
  ar: { findLeads: 'البحث عن عملاء', loadDemoLeads: 'تحميل عملاء تجريبيين', exportCsv: 'تصدير CSV', saveToGoogleSheets: 'الحفظ في Google Sheets', proposal: 'عرض السعر', demoSite: 'موقع تجريبي', salesPitch: 'نص المبيعات', whatsapp: 'WhatsApp', close: 'إغلاق', language: 'اللغة', crm: 'CRM', crmStatus: 'الحالة', crmNotes: 'ملاحظات', crmNotesPlaceholder: 'إضافة ملاحظات…', crmNextFollowUp: 'المتابعة القادمة', statusNew: 'جديد', statusContacted: 'تم التواصل', statusWhatsappSent: 'تم إرسال WhatsApp', statusProposalSent: 'تم إرسال العرض', statusNegotiation: 'تفاوض', statusWon: 'تم الفوز', statusLost: 'مفقود', dashboard: 'لوحة التحكم', bsHunter: 'BS Hunter', tasks: 'المهام', websites: 'المواقع', settings: 'الإعدادات', totalLeads: 'إجمالي العملاء', hotLeads: 'العملاء المهمون', demoSites: 'المواقع التجريبية', proposals: 'العروض', followUps: 'المتابعات', wonDeals: 'الصفقات الناجحة', nextPriorityAction: 'الإجراء التالي ذو الأولوية', businessOverview: 'نظرة عامة على العمل', dashboardSubtitle: 'العملاء ومسار المبيعات والخطوة التالية في مكان واحد.', followUpWith: 'متابعة مع', findFirstLeads: 'أنشئ قائمة العملاء الأولى', priorityLeadMessage: 'راجع العميل وجهّز العرض التجريبي وادفع المحادثة للأمام.', emptyDashboardMessage: 'افتح BS Hunter لاكتشاف الأنشطة وبناء مسار المبيعات.', openBsHunter: 'فتح BS Hunter', crmPlaceholder: 'ستظهر لوحة CRM الكاملة هنا في تحديث مستقبلي.', tasksPlaceholder: 'تخطيط المهام وسير العمل اليومي قادمان قريبًا.', websitesPlaceholder: 'ستتم إدارة المواقع المنشأة والمنشورة هنا.', settingsPlaceholder: 'ستتم إدارة تفضيلات وتكاملات Business OS هنا.', priorityReason: 'السبب', recommendedAction: 'الإجراء المقترح', priorityOverdueReason: 'موعد المتابعة المحدد متأخر.', priorityTodayReason: 'هناك متابعة مجدولة اليوم.', priorityHotNewReason: 'هذا عميل جديد بنتيجة 80 أو أكثر.', priorityContactedReason: 'تم التواصل مع هذا العميل وهو جاهز للخطوة التالية.', priorityFollowUpAction: 'تواصل مع النشاط وسجل النتيجة.', priorityContactAction: 'ابدأ التواصل بينما الفرصة قوية.', priorityPrepareAction: 'جهّز عرضًا تجريبيًا أو عرض سعر وتابع المحادثة.', priorityNoLeadReason: 'لا يوجد عميل يحتاج إلى اهتمام فوري الآن.', priorityOpenHunterAction: 'افتح BS Hunter وحمّل العملاء أو ابحث عنهم.' },
  ru: { findLeads: 'Найти лиды', loadDemoLeads: 'Загрузить демо-лиды', exportCsv: 'Экспорт CSV', saveToGoogleSheets: 'Сохранить в Google Sheets', proposal: 'Предложение', demoSite: 'Демо-сайт', salesPitch: 'Сценарий продаж', whatsapp: 'WhatsApp', close: 'Закрыть', language: 'Язык', crm: 'CRM', crmStatus: 'Статус', crmNotes: 'Заметки', crmNotesPlaceholder: 'Добавить заметки…', crmNextFollowUp: 'Следующий контакт', statusNew: 'Новый', statusContacted: 'Связались', statusWhatsappSent: 'WhatsApp отправлен', statusProposalSent: 'Предложение отправлено', statusNegotiation: 'Переговоры', statusWon: 'Выигран', statusLost: 'Потерян', dashboard: 'Панель', bsHunter: 'BS Hunter', tasks: 'Задачи', websites: 'Сайты', settings: 'Настройки', totalLeads: 'Всего лидов', hotLeads: 'Горячие лиды', demoSites: 'Демо-сайты', proposals: 'Предложения', followUps: 'Повторные контакты', wonDeals: 'Выигранные сделки', nextPriorityAction: 'Следующее приоритетное действие', businessOverview: 'Обзор бизнеса', dashboardSubtitle: 'Лиды, воронка и следующий шаг в одном месте.', followUpWith: 'Связаться с', findFirstLeads: 'Создайте первый список лидов', priorityLeadMessage: 'Проверьте лид, подготовьте демо и продолжите диалог.', emptyDashboardMessage: 'Откройте BS Hunter, чтобы найти компании и начать строить воронку.', openBsHunter: 'Открыть BS Hunter', crmPlaceholder: 'Полная CRM-панель появится здесь в будущем обновлении.', tasksPlaceholder: 'Планирование задач и ежедневные процессы скоро появятся.', websitesPlaceholder: 'Здесь будут управляться созданные и опубликованные сайты.', settingsPlaceholder: 'Здесь будут управляться настройки и интеграции Business OS.', priorityReason: 'Причина', recommendedAction: 'Рекомендуемое действие', priorityOverdueReason: 'Запланированный повторный контакт просрочен.', priorityTodayReason: 'Повторный контакт запланирован на сегодня.', priorityHotNewReason: 'Это новый лид с оценкой 80 или выше.', priorityContactedReason: 'С лидом уже связались, он готов к следующему шагу.', priorityFollowUpAction: 'Свяжитесь с компанией и запишите результат.', priorityContactAction: 'Свяжитесь впервые, пока возможность актуальна.', priorityPrepareAction: 'Подготовьте демо или предложение и продолжите диалог.', priorityNoLeadReason: 'Сейчас нет лида, требующего немедленного внимания.', priorityOpenHunterAction: 'Откройте BS Hunter и загрузите или найдите лиды.' },
}

const dashboardFilterTranslations = {
  en: { activeDashboardFilter: 'Dashboard filter', clearFilter: 'Clear Filter', filterAllRealLeads: 'All real leads', filterHotLeads: 'Hot leads (80+)', filterDemoSites: 'Created demo sites', filterProposals: 'Created or sent proposals', filterFollowUps: 'Leads with follow-ups', filterWonDeals: 'Won deals' },
  he: { activeDashboardFilter: 'מסנן לוח הבקרה', clearFilter: 'ניקוי מסנן', filterAllRealLeads: 'כל הלידים האמיתיים', filterHotLeads: 'לידים חמים (80+)', filterDemoSites: 'אתרי דמו שנוצרו', filterProposals: 'הצעות שנוצרו או נשלחו', filterFollowUps: 'לידים עם מעקב', filterWonDeals: 'עסקאות שנסגרו' },
  ar: { activeDashboardFilter: 'مرشح لوحة التحكم', clearFilter: 'مسح المرشح', filterAllRealLeads: 'كل العملاء الحقيقيين', filterHotLeads: 'العملاء المهمون (80+)', filterDemoSites: 'المواقع التجريبية المنشأة', filterProposals: 'العروض المنشأة أو المرسلة', filterFollowUps: 'العملاء ذوو المتابعة', filterWonDeals: 'الصفقات الناجحة' },
  ru: { activeDashboardFilter: 'Фильтр панели', clearFilter: 'Сбросить фильтр', filterAllRealLeads: 'Все реальные лиды', filterHotLeads: 'Горячие лиды (80+)', filterDemoSites: 'Созданные демо-сайты', filterProposals: 'Созданные или отправленные предложения', filterFollowUps: 'Лиды с повторным контактом', filterWonDeals: 'Выигранные сделки' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], dashboardFilterTranslations[language]))

const bsFundsTranslations = {
  en: { bsFunds: 'BS Funds', bsFundsSubtitle: 'Financial Leads & Marketing', bsFundsNewLeads: 'New Leads', bsFundsContacted: 'Contacted', bsFundsApplications: 'Applications', bsFundsApproved: 'Approved', bsFundsClosedDeals: 'Closed Deals', bsFundsRevenue: 'Revenue', bsFundsIntegrationPlaceholder: 'BS Funds data integration is the next step.', bsFundsShortcut: 'Financial leads' },
  he: { bsFunds: 'BS Funds', bsFundsSubtitle: 'לידים פיננסיים ושיווק', bsFundsNewLeads: 'לידים חדשים', bsFundsContacted: 'נוצר קשר', bsFundsApplications: 'בקשות', bsFundsApproved: 'אושרו', bsFundsClosedDeals: 'עסקאות שנסגרו', bsFundsRevenue: 'הכנסות', bsFundsIntegrationPlaceholder: 'חיבור הנתונים של BS Funds הוא השלב הבא.', bsFundsShortcut: 'לידים פיננסיים' },
  ar: { bsFunds: 'BS Funds', bsFundsSubtitle: 'العملاء الماليون والتسويق', bsFundsNewLeads: 'عملاء جدد', bsFundsContacted: 'تم التواصل', bsFundsApplications: 'الطلبات', bsFundsApproved: 'تمت الموافقة', bsFundsClosedDeals: 'الصفقات المغلقة', bsFundsRevenue: 'الإيرادات', bsFundsIntegrationPlaceholder: 'تكامل بيانات BS Funds هو الخطوة التالية.', bsFundsShortcut: 'عملاء ماليون' },
  ru: { bsFunds: 'BS Funds', bsFundsSubtitle: 'Финансовые лиды и маркетинг', bsFundsNewLeads: 'Новые лиды', bsFundsContacted: 'Связались', bsFundsApplications: 'Заявки', bsFundsApproved: 'Одобрено', bsFundsClosedDeals: 'Закрытые сделки', bsFundsRevenue: 'Доход', bsFundsIntegrationPlaceholder: 'Интеграция данных BS Funds — следующий шаг.', bsFundsShortcut: 'Финансовые лиды' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], bsFundsTranslations[language]))

const missionControlTranslations = {
  en: { missionControl: 'Mission Control', missionTodayLabel: "Today's priorities", missionAllClear: 'All clear. No priority actions right now.', missionOverdue: 'Follow-up is overdue', missionToday: 'Follow-up scheduled today', missionHotUncontacted: 'Hot lead not contacted', missionProposalMissing: 'Proposal has not been sent', missionDemoMissing: 'Demo site has not been created', missionSalesPitchMissing: 'Sales pitch has not been completed', missionWhatsappMissing: 'Ready to send WhatsApp', missionRecentlyAdded: 'Recently added lead', missionOpenCrm: 'Open CRM', missionOpenSalesPitch: 'Sales Pitch', missionOpenProposal: 'Open Proposal', missionOpenDemo: 'Open Demo', missionOpenWhatsapp: 'WhatsApp', missionOpenHunter: 'Open Lead' },
  he: { missionControl: 'מרכז משימות', missionTodayLabel: 'העדיפויות להיום', missionAllClear: 'הכול מסודר. אין כרגע פעולות בעדיפות.', missionOverdue: 'מועד המעקב עבר', missionToday: 'מעקב נקבע להיום', missionHotUncontacted: 'ליד חם שטרם נוצר איתו קשר', missionProposalMissing: 'הצעה טרם נשלחה', missionDemoMissing: 'אתר דמו טרם נוצר', missionSalesPitchMissing: 'שיחת המכירה טרם הושלמה', missionWhatsappMissing: 'מוכן לשליחת WhatsApp', missionRecentlyAdded: 'ליד שנוסף לאחרונה', missionOpenCrm: 'פתיחת CRM', missionOpenSalesPitch: 'שיחת מכירה', missionOpenProposal: 'פתיחת הצעה', missionOpenDemo: 'פתיחת דמו', missionOpenWhatsapp: 'WhatsApp', missionOpenHunter: 'פתיחת ליד' },
  ar: { missionControl: 'مركز المهام', missionTodayLabel: 'أولويات اليوم', missionAllClear: 'كل شيء منظم. لا توجد إجراءات ذات أولوية الآن.', missionOverdue: 'موعد المتابعة متأخر', missionToday: 'متابعة مجدولة اليوم', missionHotUncontacted: 'عميل مهم لم يتم التواصل معه', missionProposalMissing: 'لم يتم إرسال العرض', missionDemoMissing: 'لم يتم إنشاء الموقع التجريبي', missionSalesPitchMissing: 'لم تكتمل محادثة المبيعات', missionWhatsappMissing: 'جاهز لإرسال WhatsApp', missionRecentlyAdded: 'عميل مضاف حديثًا', missionOpenCrm: 'فتح CRM', missionOpenSalesPitch: 'محادثة المبيعات', missionOpenProposal: 'فتح العرض', missionOpenDemo: 'فتح التجربة', missionOpenWhatsapp: 'WhatsApp', missionOpenHunter: 'فتح العميل' },
  ru: { missionControl: 'Центр управления', missionTodayLabel: 'Приоритеты на сегодня', missionAllClear: 'Всё выполнено. Сейчас нет приоритетных действий.', missionOverdue: 'Повторный контакт просрочен', missionToday: 'Повторный контакт назначен на сегодня', missionHotUncontacted: 'С горячим лидом ещё не связались', missionProposalMissing: 'Предложение ещё не отправлено', missionDemoMissing: 'Демо-сайт ещё не создан', missionSalesPitchMissing: 'Продажа ещё не отработана', missionWhatsappMissing: 'Готово к отправке в WhatsApp', missionRecentlyAdded: 'Недавно добавленный лид', missionOpenCrm: 'Открыть CRM', missionOpenSalesPitch: 'Продажа', missionOpenProposal: 'Открыть предложение', missionOpenDemo: 'Открыть демо', missionOpenWhatsapp: 'WhatsApp', missionOpenHunter: 'Открыть лид' },
}

missionControlTranslations.en.missionTodayLabel = "Today's priorities"
missionControlTranslations.he.missionTodayLabel = 'העדיפויות להיום'
missionControlTranslations.ar.missionTodayLabel = 'أولويات اليوم'
missionControlTranslations.ru.missionTodayLabel = 'Приоритеты на сегодня'

Object.keys(translations).forEach((language) => Object.assign(translations[language], missionControlTranslations[language]))

const taskModuleTranslations = {
  en: { addTask: 'Add Task', editTask: 'Edit Task', deleteTask: 'Delete Task', markComplete: 'Mark Complete', saveTask: 'Save Task', cancel: 'Cancel', taskTitle: 'Title', taskDescription: 'Description', taskProject: 'Project', taskCategory: 'Category', taskPriority: 'Priority', taskStatus: 'Status', taskDueDate: 'Due date', taskAssignee: 'Assigned person or agent', taskRevenue: 'Revenue impact', taskBlocking: 'Blocking', taskNotes: 'Notes', taskCreated: 'Created', taskCompletedDate: 'Completed', taskCritical: 'Critical', taskImportant: 'Important', taskCompletedPriority: 'Completed', taskOpen: 'Open', taskInProgress: 'In Progress', taskBlocked: 'Blocked', taskCompleted: 'Completed', taskStatus_open: 'Open', 'taskStatus_in-progress': 'In Progress', taskStatus_blocked: 'Blocked', taskStatus_completed: 'Completed', allPriorities: 'All priorities', allProjects: 'All projects', allStatuses: 'All statuses', allCategories: 'All categories', activeTasks: 'Top 20 active tasks', openTasks: 'Open Tasks' },
  he: { addTask: 'הוספת משימה', editTask: 'עריכת משימה', deleteTask: 'מחיקת משימה', markComplete: 'סימון כהושלמה', saveTask: 'שמירת משימה', cancel: 'ביטול', taskTitle: 'כותרת', taskDescription: 'תיאור', taskProject: 'פרויקט', taskCategory: 'קטגוריה', taskPriority: 'עדיפות', taskStatus: 'סטטוס', taskDueDate: 'תאריך יעד', taskAssignee: 'אדם או סוכן אחראי', taskRevenue: 'השפעה על הכנסות', taskBlocking: 'חוסמת', taskNotes: 'הערות', taskCreated: 'נוצרה', taskCompletedDate: 'הושלמה', taskCritical: 'קריטית', taskImportant: 'חשובה', taskCompletedPriority: 'הושלמה', taskOpen: 'פתוחה', taskInProgress: 'בתהליך', taskBlocked: 'חסומה', taskCompleted: 'הושלמה', taskStatus_open: 'פתוחה', 'taskStatus_in-progress': 'בתהליך', taskStatus_blocked: 'חסומה', taskStatus_completed: 'הושלמה', allPriorities: 'כל העדיפויות', allProjects: 'כל הפרויקטים', allStatuses: 'כל הסטטוסים', allCategories: 'כל הקטגוריות', activeTasks: '20 המשימות הפעילות המובילות', openTasks: 'פתיחת משימות' },
  ar: { addTask: 'إضافة مهمة', editTask: 'تعديل المهمة', deleteTask: 'حذف المهمة', markComplete: 'تحديد كمكتملة', saveTask: 'حفظ المهمة', cancel: 'إلغاء', taskTitle: 'العنوان', taskDescription: 'الوصف', taskProject: 'المشروع', taskCategory: 'الفئة', taskPriority: 'الأولوية', taskStatus: 'الحالة', taskDueDate: 'تاريخ الاستحقاق', taskAssignee: 'الشخص أو الوكيل المسؤول', taskRevenue: 'تأثير الإيرادات', taskBlocking: 'حاجبة', taskNotes: 'ملاحظات', taskCreated: 'تاريخ الإنشاء', taskCompletedDate: 'تاريخ الإكمال', taskCritical: 'حرجة', taskImportant: 'مهمة', taskCompletedPriority: 'مكتملة', taskOpen: 'مفتوحة', taskInProgress: 'قيد التنفيذ', taskBlocked: 'محجوبة', taskCompleted: 'مكتملة', taskStatus_open: 'مفتوحة', 'taskStatus_in-progress': 'قيد التنفيذ', taskStatus_blocked: 'محجوبة', taskStatus_completed: 'مكتملة', allPriorities: 'كل الأولويات', allProjects: 'كل المشاريع', allStatuses: 'كل الحالات', allCategories: 'كل الفئات', activeTasks: 'أعلى 20 مهمة نشطة', openTasks: 'فتح المهام' },
  ru: { addTask: 'Добавить задачу', editTask: 'Изменить задачу', deleteTask: 'Удалить задачу', markComplete: 'Завершить', saveTask: 'Сохранить задачу', cancel: 'Отмена', taskTitle: 'Название', taskDescription: 'Описание', taskProject: 'Проект', taskCategory: 'Категория', taskPriority: 'Приоритет', taskStatus: 'Статус', taskDueDate: 'Срок', taskAssignee: 'Ответственный или агент', taskRevenue: 'Влияние на доход', taskBlocking: 'Блокирует', taskNotes: 'Заметки', taskCreated: 'Создана', taskCompletedDate: 'Завершена', taskCritical: 'Критическая', taskImportant: 'Важная', taskCompletedPriority: 'Завершена', taskOpen: 'Открыта', taskInProgress: 'В работе', taskBlocked: 'Заблокирована', taskCompleted: 'Завершена', taskStatus_open: 'Открыта', 'taskStatus_in-progress': 'В работе', taskStatus_blocked: 'Заблокирована', taskStatus_completed: 'Завершена', allPriorities: 'Все приоритеты', allProjects: 'Все проекты', allStatuses: 'Все статусы', allCategories: 'Все категории', activeTasks: '20 главных активных задач', openTasks: 'Открыть задачи' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], taskModuleTranslations[language]))

const taskRoadmapTranslations = {
  en: { allTasks: 'All Tasks', taskTotal: 'Total tasks', previousPage: 'Previous', nextPage: 'Next', page: 'Page', category_BusinessOS: 'Business OS', category_BSHunter: 'BS Hunter', category_LeadSearch: 'Lead Search', category_DemoWebsites: 'Demo Websites', category_Sales: 'Sales', category_CRM: 'CRM', category_Proposals: 'Proposals', category_WhatsApp: 'WhatsApp', category_Payments: 'Payments', category_BSFunds: 'BS Funds', category_Marketing: 'Marketing', category_Automation: 'Automation', category_Infrastructure: 'Infrastructure', category_GlobalLanguages: 'Global Languages', category_FutureDevelopment: 'Future Development' },
  he: { allTasks: 'כל המשימות', taskTotal: 'סה״כ משימות', previousPage: 'הקודם', nextPage: 'הבא', page: 'עמוד', category_BusinessOS: 'Business OS', category_BSHunter: 'BS Hunter', category_LeadSearch: 'חיפוש לידים', category_DemoWebsites: 'אתרי דמו', category_Sales: 'מכירות', category_CRM: 'CRM', category_Proposals: 'הצעות', category_WhatsApp: 'WhatsApp', category_Payments: 'תשלומים', category_BSFunds: 'BS Funds', category_Marketing: 'שיווק', category_Automation: 'אוטומציה', category_Infrastructure: 'תשתיות', category_GlobalLanguages: 'שפות גלובליות', category_FutureDevelopment: 'פיתוח עתידי' },
  ar: { allTasks: 'كل المهام', taskTotal: 'إجمالي المهام', previousPage: 'السابق', nextPage: 'التالي', page: 'صفحة', category_BusinessOS: 'Business OS', category_BSHunter: 'BS Hunter', category_LeadSearch: 'البحث عن العملاء', category_DemoWebsites: 'المواقع التجريبية', category_Sales: 'المبيعات', category_CRM: 'CRM', category_Proposals: 'العروض', category_WhatsApp: 'WhatsApp', category_Payments: 'المدفوعات', category_BSFunds: 'BS Funds', category_Marketing: 'التسويق', category_Automation: 'الأتمتة', category_Infrastructure: 'البنية التحتية', category_GlobalLanguages: 'اللغات العالمية', category_FutureDevelopment: 'التطوير المستقبلي' },
  ru: { allTasks: 'Все задачи', taskTotal: 'Всего задач', previousPage: 'Назад', nextPage: 'Далее', page: 'Страница', category_BusinessOS: 'Business OS', category_BSHunter: 'BS Hunter', category_LeadSearch: 'Поиск лидов', category_DemoWebsites: 'Демо-сайты', category_Sales: 'Продажи', category_CRM: 'CRM', category_Proposals: 'Предложения', category_WhatsApp: 'WhatsApp', category_Payments: 'Платежи', category_BSFunds: 'BS Funds', category_Marketing: 'Маркетинг', category_Automation: 'Автоматизация', category_Infrastructure: 'Инфраструктура', category_GlobalLanguages: 'Глобальные языки', category_FutureDevelopment: 'Будущая разработка' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], taskRoadmapTranslations[language]))

const manualLeadTranslations = {
  en: { addLeadManually: 'Add Lead Manually', manualBusinessName: 'Business Name', manualWebsite: 'Website', manualPhone: 'Phone', manualAddress: 'Address', manualRating: 'Rating', manualReviews: 'Reviews Count', manualMapsUrl: 'Google Maps URL', saveLead: 'Save Lead', manualBusinessRequired: 'Business name is required.', manualDuplicateLead: 'This lead already exists.', manualLeadSaved: 'Manual lead saved.' },
  he: { addLeadManually: 'הוספת ליד ידנית', manualBusinessName: 'שם העסק', manualWebsite: 'אתר', manualPhone: 'טלפון', manualAddress: 'כתובת', manualRating: 'דירוג', manualReviews: 'מספר ביקורות', manualMapsUrl: 'קישור Google Maps', saveLead: 'שמירת ליד', manualBusinessRequired: 'חובה להזין שם עסק.', manualDuplicateLead: 'הליד הזה כבר קיים.', manualLeadSaved: 'הליד הידני נשמר.' },
  ar: { addLeadManually: 'إضافة عميل يدويًا', manualBusinessName: 'اسم النشاط', manualWebsite: 'الموقع', manualPhone: 'الهاتف', manualAddress: 'العنوان', manualRating: 'التقييم', manualReviews: 'عدد المراجعات', manualMapsUrl: 'رابط Google Maps', saveLead: 'حفظ العميل', manualBusinessRequired: 'اسم النشاط مطلوب.', manualDuplicateLead: 'هذا العميل موجود بالفعل.', manualLeadSaved: 'تم حفظ العميل اليدوي.' },
  ru: { addLeadManually: 'Добавить лид вручную', manualBusinessName: 'Название компании', manualWebsite: 'Сайт', manualPhone: 'Телефон', manualAddress: 'Адрес', manualRating: 'Рейтинг', manualReviews: 'Количество отзывов', manualMapsUrl: 'Ссылка Google Maps', saveLead: 'Сохранить лид', manualBusinessRequired: 'Название компании обязательно.', manualDuplicateLead: 'Этот лид уже существует.', manualLeadSaved: 'Лид сохранён вручную.' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], manualLeadTranslations[language]))

const projectTranslations = {
  en: { projects: 'Projects', projectStatusActive: 'Active Development', projectPhasePreRevenue: 'Pre-Revenue / Production Launch', projectOverallProgress: 'Overall progress', projectLastUpdated: 'Last updated', updateProjectStatus: 'Update Project Status', projectTab_overview: 'Overview', projectTab_nextTasks: 'Next 10 Tasks', projectTab_modules: 'Modules', projectTab_issues: 'Known Issues', projectTab_documents: 'Documents', projectCurrentTask: 'Current Active Task', projectNoActiveTask: 'No incomplete task is available.', openRelatedModule: 'Open Related Module', projectRevenueFlow: 'Revenue Flow', projectCompletedModules: 'Completed Modules', projectIncompleteModules: 'Incomplete Modules', projectDocumentPreview: 'Project document', projectDocumentsReadOnly: 'This browser view mirrors the markdown files and does not write to them.', openCrm: 'Open CRM', openWebsites: 'Open Websites', projectIssuePaidSearch: 'Paid lead search requires provider billing and a deployed backend.', projectIssueDeployment: 'Production deployment has not been completed or smoke-tested on a public URL.', projectIssueDemoQuality: 'Demo website quality requires improvement before paid customer delivery.', projectIssueSheets: 'Google Sheets requires a configured Apps Script endpoint.', projectIssueLocalStorage: 'Operational data relies on localStorage and can be lost when browser storage is cleared.', projectIssueCors: 'Paid backend CORS remains configured for local development.', projectIssueMissionControl: 'Mission Control does not yet create a separate sales-stage task for every lead.', projectIssueTests: 'There is no automated test suite beyond build and lint.', projectDocStatus: 'Current goals, verified features, incomplete work, issues, run instructions, and next priorities.', projectDocTasks: 'Durable 100+ task roadmap with priorities, blockers, dependencies, and status.', projectDocDecisions: 'Permanent architecture and product decisions.', projectDocGuide: 'Beginner-friendly instructions for running, testing, reviewing, and restoring the project.', projectDocChangelog: 'Chronological record of verified completed development work.', projectDocAgents: 'Mandatory rules for every future coding agent.', flow_Lead: 'Lead', flow_CRM: 'CRM', flow_DemoSite: 'Demo Site', flow_SalesPitch: 'Sales Pitch', flow_Proposal: 'Proposal', flow_WhatsApp: 'WhatsApp', flow_Payment: 'Payment', flow_RealWebsite: 'Real Website', flow_Deployment: 'Deployment', flow_CustomerSupport: 'Customer Support' },
  he: { projects: 'פרויקטים', projectStatusActive: 'פיתוח פעיל', projectPhasePreRevenue: 'טרום הכנסות / השקת ייצור', projectOverallProgress: 'התקדמות כוללת', projectLastUpdated: 'עודכן לאחרונה', updateProjectStatus: 'עדכון מצב הפרויקט', projectTab_overview: 'סקירה', projectTab_nextTasks: '10 המשימות הבאות', projectTab_modules: 'מודולים', projectTab_issues: 'בעיות ידועות', projectTab_documents: 'מסמכים', projectCurrentTask: 'משימה פעילה נוכחית', projectNoActiveTask: 'אין משימה לא גמורה זמינה.', openRelatedModule: 'פתיחת המודול הקשור', projectRevenueFlow: 'תהליך הכנסות', projectCompletedModules: 'מודולים שהושלמו', projectIncompleteModules: 'מודולים שלא הושלמו', projectDocumentPreview: 'מסמך פרויקט', projectDocumentsReadOnly: 'תצוגת הדפדפן משקפת את קובצי Markdown ואינה כותבת אליהם.', openCrm: 'פתיחת CRM', openWebsites: 'פתיחת אתרים', projectIssuePaidSearch: 'חיפוש לידים בתשלום דורש חיוב ספק ושרת פעיל.', projectIssueDeployment: 'הפריסה לייצור טרם הושלמה או נבדקה בכתובת ציבורית.', projectIssueDemoQuality: 'איכות אתר הדמו דורשת שיפור לפני מסירה ללקוחות משלמים.', projectIssueSheets: 'Google Sheets דורש כתובת Apps Script מוגדרת.', projectIssueLocalStorage: 'המידע התפעולי נשמר ב-localStorage ועלול להימחק עם ניקוי הדפדפן.', projectIssueCors: 'ה-CORS של השרת בתשלום עדיין מוגדר לפיתוח מקומי.', projectIssueMissionControl: 'מרכז המשימות עדיין לא יוצר משימת שלב מכירה נפרדת לכל ליד.', projectIssueTests: 'אין בדיקות אוטומטיות מעבר לבנייה ולינט.', projectDocStatus: 'מטרות, יכולות מאומתות, עבודה חסרה, בעיות, הוראות והרשימה הבאה.', projectDocTasks: 'מפת דרכים קבועה של 100+ משימות עם עדיפויות ותלויות.', projectDocDecisions: 'החלטות מוצר וארכיטקטורה קבועות.', projectDocGuide: 'הוראות פשוטות להפעלה, בדיקה, סקירה ושחזור.', projectDocChangelog: 'יומן כרונולוגי של עבודה מאומתת שהושלמה.', projectDocAgents: 'כללים מחייבים לכל סוכן קוד עתידי.', flow_Lead: 'ליד', flow_CRM: 'CRM', flow_DemoSite: 'אתר דמו', flow_SalesPitch: 'שיחת מכירה', flow_Proposal: 'הצעה', flow_WhatsApp: 'WhatsApp', flow_Payment: 'תשלום', flow_RealWebsite: 'אתר אמיתי', flow_Deployment: 'פריסה', flow_CustomerSupport: 'תמיכת לקוחות' },
  ar: { projects: 'المشاريع', projectStatusActive: 'تطوير نشط', projectPhasePreRevenue: 'ما قبل الإيرادات / إطلاق الإنتاج', projectOverallProgress: 'التقدم الإجمالي', projectLastUpdated: 'آخر تحديث', updateProjectStatus: 'تحديث حالة المشروع', projectTab_overview: 'نظرة عامة', projectTab_nextTasks: 'المهام العشر التالية', projectTab_modules: 'الوحدات', projectTab_issues: 'المشكلات المعروفة', projectTab_documents: 'المستندات', projectCurrentTask: 'المهمة النشطة الحالية', projectNoActiveTask: 'لا توجد مهمة غير مكتملة.', openRelatedModule: 'فتح الوحدة المرتبطة', projectRevenueFlow: 'تدفق الإيرادات', projectCompletedModules: 'الوحدات المكتملة', projectIncompleteModules: 'الوحدات غير المكتملة', projectDocumentPreview: 'مستند المشروع', projectDocumentsReadOnly: 'تعكس هذه الشاشة ملفات Markdown ولا تكتب إليها.', openCrm: 'فتح CRM', openWebsites: 'فتح المواقع', projectIssuePaidSearch: 'يتطلب بحث العملاء المدفوع فوترة المزود وخادمًا منشورًا.', projectIssueDeployment: 'لم يكتمل نشر الإنتاج أو اختباره على رابط عام.', projectIssueDemoQuality: 'تحتاج جودة الموقع التجريبي إلى تحسين قبل تسليمه لعميل مدفوع.', projectIssueSheets: 'يتطلب Google Sheets رابط Apps Script مهيأ.', projectIssueLocalStorage: 'تعتمد البيانات التشغيلية على localStorage وقد تضيع عند مسح المتصفح.', projectIssueCors: 'لا يزال CORS للخادم المدفوع مهيأ للتطوير المحلي.', projectIssueMissionControl: 'لا ينشئ مركز المهام بعد مهمة مرحلة مبيعات منفصلة لكل عميل.', projectIssueTests: 'لا توجد اختبارات تلقائية غير البناء والفحص.', projectDocStatus: 'الأهداف والميزات المؤكدة والعمل الناقص والمشكلات وتعليمات التشغيل والأولويات.', projectDocTasks: 'خارطة طريق دائمة تضم أكثر من 100 مهمة وأولويات وتبعيات.', projectDocDecisions: 'قرارات المنتج والبنية الدائمة.', projectDocGuide: 'تعليمات بسيطة للتشغيل والاختبار والمراجعة والاستعادة.', projectDocChangelog: 'سجل زمني للعمل المؤكد المكتمل.', projectDocAgents: 'قواعد إلزامية لكل وكيل برمجي مستقبلي.', flow_Lead: 'عميل', flow_CRM: 'CRM', flow_DemoSite: 'موقع تجريبي', flow_SalesPitch: 'محادثة المبيعات', flow_Proposal: 'عرض', flow_WhatsApp: 'WhatsApp', flow_Payment: 'دفع', flow_RealWebsite: 'موقع حقيقي', flow_Deployment: 'نشر', flow_CustomerSupport: 'دعم العملاء' },
  ru: { projects: 'Проекты', projectStatusActive: 'Активная разработка', projectPhasePreRevenue: 'До выручки / производственный запуск', projectOverallProgress: 'Общий прогресс', projectLastUpdated: 'Последнее обновление', updateProjectStatus: 'Обновить статус проекта', projectTab_overview: 'Обзор', projectTab_nextTasks: 'Следующие 10 задач', projectTab_modules: 'Модули', projectTab_issues: 'Известные проблемы', projectTab_documents: 'Документы', projectCurrentTask: 'Текущая активная задача', projectNoActiveTask: 'Нет незавершённой задачи.', openRelatedModule: 'Открыть связанный модуль', projectRevenueFlow: 'Поток выручки', projectCompletedModules: 'Завершённые модули', projectIncompleteModules: 'Незавершённые модули', projectDocumentPreview: 'Документ проекта', projectDocumentsReadOnly: 'Этот экран отражает Markdown-файлы и не записывает в них.', openCrm: 'Открыть CRM', openWebsites: 'Открыть сайты', projectIssuePaidSearch: 'Платный поиск лидов требует биллинга провайдера и опубликованного сервера.', projectIssueDeployment: 'Продакшен ещё не опубликован и не проверен по публичному URL.', projectIssueDemoQuality: 'Качество демо-сайта нужно улучшить перед передачей платным клиентам.', projectIssueSheets: 'Google Sheets требует настроенный адрес Apps Script.', projectIssueLocalStorage: 'Операционные данные зависят от localStorage и могут быть удалены очисткой браузера.', projectIssueCors: 'CORS платного сервера пока настроен для локальной разработки.', projectIssueMissionControl: 'Центр управления ещё не создаёт отдельную задачу этапа продаж для каждого лида.', projectIssueTests: 'Нет автоматических тестов кроме сборки и линта.', projectDocStatus: 'Цели, подтверждённые функции, незавершённая работа, проблемы, запуск и приоритеты.', projectDocTasks: 'Постоянная дорожная карта из 100+ задач с приоритетами и зависимостями.', projectDocDecisions: 'Постоянные решения по продукту и архитектуре.', projectDocGuide: 'Простые инструкции по запуску, тестированию, проверке и восстановлению.', projectDocChangelog: 'Хронологический журнал подтверждённой завершённой работы.', projectDocAgents: 'Обязательные правила для будущих программных агентов.', flow_Lead: 'Лид', flow_CRM: 'CRM', flow_DemoSite: 'Демо-сайт', flow_SalesPitch: 'Продажа', flow_Proposal: 'Предложение', flow_WhatsApp: 'WhatsApp', flow_Payment: 'Оплата', flow_RealWebsite: 'Реальный сайт', flow_Deployment: 'Публикация', flow_CustomerSupport: 'Поддержка клиентов' },
}

const projectModuleLabels = { module_BusinessOS: 'Business OS', module_BSHunter: 'BS Hunter', module_BSFundsshell: 'BS Funds shell', module_CRM: 'CRM', module_Tasks: 'Tasks', module_MissionControl: 'Mission Control', module_DemoWebsiteBuilder: 'Demo Website Builder', module_ProposalGenerator: 'Proposal Generator', module_SalesCenter: 'Sales Center', module_WhatsApp: 'WhatsApp', module_Languages: 'Languages', module_AICenter: 'AI Center', module_RealLeadSearch: 'Real Lead Search', module_RealWebsiteBuilder: 'Real Website Builder', module_Deployment: 'Deployment', module_Payments: 'Payments', module_GlobalCRM: 'Global CRM', module_Automation: 'Automation', module_ClientSuccess: 'Client Success', module_AIManager: 'AI Manager' }

Object.keys(translations).forEach((language) => Object.assign(translations[language], projectTranslations[language], projectModuleLabels))

const projectCommandTranslations = {
  en: { projectCommandCenter: 'Project Command Center', projectCommandSubtitle: 'Track progress, priorities, issues, and next actions across the entire Business OS.', projectTasksCompleted: 'Tasks Completed', projectActiveProjects: 'Active projects', projectOpenIssues: 'Open issues', projectBlockedTasks: 'Blocked tasks', projectEstimatedTime: 'Estimated time', projectNotAvailable: 'Not available', projectYes: 'Yes', projectNo: 'No', projectTab_nextTasks: 'Next Tasks' },
  he: { projectCommandCenter: 'מרכז השליטה בפרויקט', projectCommandSubtitle: 'מעקב אחר התקדמות, עדיפויות, בעיות ופעולות הבאות בכל Business OS.', projectTasksCompleted: 'משימות הושלמו', projectActiveProjects: 'פרויקטים פעילים', projectOpenIssues: 'בעיות פתוחות', projectBlockedTasks: 'משימות חסומות', projectEstimatedTime: 'זמן משוער', projectNotAvailable: 'לא זמין', projectYes: 'כן', projectNo: 'לא', projectTab_nextTasks: 'המשימות הבאות' },
  ar: { projectCommandCenter: 'مركز قيادة المشروع', projectCommandSubtitle: 'تتبّع التقدم والأولويات والمشكلات والإجراءات التالية في Business OS بالكامل.', projectTasksCompleted: 'مهام مكتملة', projectActiveProjects: 'مشاريع نشطة', projectOpenIssues: 'مشكلات مفتوحة', projectBlockedTasks: 'مهام محجوبة', projectEstimatedTime: 'الوقت المقدر', projectNotAvailable: 'غير متاح', projectYes: 'نعم', projectNo: 'لا', projectTab_nextTasks: 'المهام التالية' },
  ru: { projectCommandCenter: 'Центр управления проектом', projectCommandSubtitle: 'Отслеживайте прогресс, приоритеты, проблемы и следующие действия во всей Business OS.', projectTasksCompleted: 'Задач завершено', projectActiveProjects: 'Активные проекты', projectOpenIssues: 'Открытые проблемы', projectBlockedTasks: 'Заблокированные задачи', projectEstimatedTime: 'Оценка времени', projectNotAvailable: 'Нет данных', projectYes: 'Да', projectNo: 'Нет', projectTab_nextTasks: 'Следующие задачи' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], projectCommandTranslations[language]))

const aiCenterTranslations = {
  en: { aiCenter: 'AI Center', aiCenterSubtitle: 'Secure OpenAI tools for Business OS.', aiConnected: 'Connected', aiNotConnected: 'Not Connected', aiSelectedModel: 'Selected model', aiTestConnection: 'Test Connection', aiSecureBackend: 'Secure backend connection', aiBillingRequired: 'OpenAI API billing and a backend API key are required. Business OS remains fully usable without them.', aiBackendUnavailable: 'The AI backend is not configured for this deployment.', aiRequestFailed: 'The AI request could not be completed.', aiRequestInput: 'AI request', aiRequestPlaceholder: 'Ask the Business OS assistant...', aiSend: 'Send', aiSending: 'Sending...', aiResponse: 'Response', aiResponsePlaceholder: 'The AI response will appear here.', aiEmptyResponse: 'The AI response was empty.', aiRecentActivity: 'Recent activity', aiClearHistory: 'Clear history', aiNoActivity: 'No AI activity yet.', aiSuccess: 'Success', aiFailure: 'Failure', aiSummarizeProject: 'Summarize Project Status', aiSummarizePrompt: 'Summarize the current Business OS project status. Highlight progress, the active task, the highest-priority next tasks, known issues, and practical next actions.', aiActionTestConnection: 'Test Connection', aiActionSummarizeProject: 'Summarize Project Status', aiActionRequest: 'AI Request' },
  he: { aiCenter: 'מרכז AI', aiCenterSubtitle: 'כלי OpenAI מאובטחים עבור Business OS.', aiConnected: 'מחובר', aiNotConnected: 'לא מחובר', aiSelectedModel: 'מודל נבחר', aiTestConnection: 'בדיקת חיבור', aiSecureBackend: 'חיבור מאובטח לשרת', aiBillingRequired: 'נדרשים חיוב OpenAI ומפתח API בשרת. Business OS נשאר זמין לחלוטין גם בלעדיהם.', aiBackendUnavailable: 'שרת ה-AI אינו מוגדר בפריסה זו.', aiRequestFailed: 'לא ניתן להשלים את בקשת ה-AI.', aiRequestInput: 'בקשת AI', aiRequestPlaceholder: 'שאלו את עוזר Business OS...', aiSend: 'שליחה', aiSending: 'שולח...', aiResponse: 'תשובה', aiResponsePlaceholder: 'תשובת ה-AI תופיע כאן.', aiEmptyResponse: 'תשובת ה-AI הייתה ריקה.', aiRecentActivity: 'פעילות אחרונה', aiClearHistory: 'ניקוי היסטוריה', aiNoActivity: 'אין עדיין פעילות AI.', aiSuccess: 'הצלחה', aiFailure: 'כישלון', aiSummarizeProject: 'סיכום מצב הפרויקט', aiSummarizePrompt: 'סכם את המצב הנוכחי של פרויקט Business OS. הדגש התקדמות, משימה פעילה, המשימות הבאות בעדיפות, בעיות ידועות ופעולות מעשיות.', aiActionTestConnection: 'בדיקת חיבור', aiActionSummarizeProject: 'סיכום מצב הפרויקט', aiActionRequest: 'בקשת AI' },
  ar: { aiCenter: 'مركز AI', aiCenterSubtitle: 'أدوات OpenAI آمنة لـ Business OS.', aiConnected: 'متصل', aiNotConnected: 'غير متصل', aiSelectedModel: 'النموذج المحدد', aiTestConnection: 'اختبار الاتصال', aiSecureBackend: 'اتصال آمن بالخادم', aiBillingRequired: 'تتطلب OpenAI فوترة ومفتاح API في الخادم. يظل Business OS قابلًا للاستخدام بالكامل من دونهما.', aiBackendUnavailable: 'خادم AI غير مهيأ لهذا النشر.', aiRequestFailed: 'تعذر إكمال طلب AI.', aiRequestInput: 'طلب AI', aiRequestPlaceholder: 'اسأل مساعد Business OS...', aiSend: 'إرسال', aiSending: 'جارٍ الإرسال...', aiResponse: 'الرد', aiResponsePlaceholder: 'سيظهر رد AI هنا.', aiEmptyResponse: 'كان رد AI فارغًا.', aiRecentActivity: 'النشاط الأخير', aiClearHistory: 'مسح السجل', aiNoActivity: 'لا يوجد نشاط AI بعد.', aiSuccess: 'نجاح', aiFailure: 'فشل', aiSummarizeProject: 'تلخيص حالة المشروع', aiSummarizePrompt: 'لخص الحالة الحالية لمشروع Business OS. أبرز التقدم والمهمة النشطة وأهم المهام التالية والمشكلات المعروفة والإجراءات العملية.', aiActionTestConnection: 'اختبار الاتصال', aiActionSummarizeProject: 'تلخيص حالة المشروع', aiActionRequest: 'طلب AI' },
  ru: { aiCenter: 'AI-центр', aiCenterSubtitle: 'Безопасные инструменты OpenAI для Business OS.', aiConnected: 'Подключено', aiNotConnected: 'Не подключено', aiSelectedModel: 'Выбранная модель', aiTestConnection: 'Проверить подключение', aiSecureBackend: 'Безопасное серверное подключение', aiBillingRequired: 'Требуются биллинг OpenAI и API-ключ на сервере. Business OS полностью работает и без них.', aiBackendUnavailable: 'AI-сервер не настроен для этого развёртывания.', aiRequestFailed: 'Не удалось выполнить AI-запрос.', aiRequestInput: 'AI-запрос', aiRequestPlaceholder: 'Спросите помощника Business OS...', aiSend: 'Отправить', aiSending: 'Отправка...', aiResponse: 'Ответ', aiResponsePlaceholder: 'Ответ AI появится здесь.', aiEmptyResponse: 'Ответ AI был пустым.', aiRecentActivity: 'Недавняя активность', aiClearHistory: 'Очистить историю', aiNoActivity: 'AI-активности пока нет.', aiSuccess: 'Успешно', aiFailure: 'Ошибка', aiSummarizeProject: 'Сводка статуса проекта', aiSummarizePrompt: 'Кратко изложи текущий статус проекта Business OS. Выдели прогресс, активную задачу, главные следующие задачи, известные проблемы и практические действия.', aiActionTestConnection: 'Проверка подключения', aiActionSummarizeProject: 'Сводка статуса проекта', aiActionRequest: 'AI-запрос' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], aiCenterTranslations[language]))

const aiCenterActionTranslations = {
  en: { aiWhatNext: 'What Should I Do Next?', aiWhatNextPrompt: 'Based only on the supplied project context, tell me the single best next action and why.', aiFindBlockers: 'Find Blocking Issues', aiFindBlockersPrompt: 'Identify the blocking issues in the supplied project context and recommend the safest order to resolve them.', aiPrioritizeTasks: 'Prioritize Top 10 Tasks', aiPrioritizeTasksPrompt: 'Prioritize the supplied top 10 tasks. Explain the order using urgency, blocking status, and revenue impact.', aiActionWhatNext: 'What Should I Do Next?', aiActionFindBlockers: 'Find Blocking Issues', aiActionPrioritizeTasks: 'Prioritize Top 10 Tasks' },
  he: { aiWhatNext: 'מה עליי לעשות עכשיו?', aiWhatNextPrompt: 'בהתבסס רק על הקשר הפרויקט שסופק, אמור לי מהי הפעולה הבאה הטובה ביותר ומדוע.', aiFindBlockers: 'איתור בעיות חוסמות', aiFindBlockersPrompt: 'זהה את הבעיות החוסמות בהקשר הפרויקט שסופק והמלץ על הסדר הבטוח ביותר לפתרונן.', aiPrioritizeTasks: 'תעדוף 10 המשימות המובילות', aiPrioritizeTasksPrompt: 'תעדף את 10 המשימות שסופקו. הסבר את הסדר לפי דחיפות, מצב חסימה והשפעה על הכנסות.', aiActionWhatNext: 'מה עליי לעשות עכשיו?', aiActionFindBlockers: 'איתור בעיות חוסמות', aiActionPrioritizeTasks: 'תעדוף 10 המשימות המובילות' },
  ar: { aiWhatNext: 'ماذا يجب أن أفعل الآن؟', aiWhatNextPrompt: 'اعتمادًا فقط على سياق المشروع المرسل، حدد أفضل إجراء تالٍ وسبب اختياره.', aiFindBlockers: 'اكتشاف المشكلات الحاجبة', aiFindBlockersPrompt: 'حدد المشكلات الحاجبة في سياق المشروع المرسل واقترح الترتيب الأكثر أمانًا لحلها.', aiPrioritizeTasks: 'ترتيب أهم 10 مهام', aiPrioritizeTasksPrompt: 'رتب المهام العشر المرسلة حسب الأولوية واشرح الترتيب بناءً على الاستعجال والحجب وتأثير الإيرادات.', aiActionWhatNext: 'ماذا يجب أن أفعل الآن؟', aiActionFindBlockers: 'اكتشاف المشكلات الحاجبة', aiActionPrioritizeTasks: 'ترتيب أهم 10 مهام' },
  ru: { aiWhatNext: 'Что мне делать дальше?', aiWhatNextPrompt: 'Опираясь только на переданный контекст проекта, назови одно лучшее следующее действие и объясни почему.', aiFindBlockers: 'Найти блокирующие проблемы', aiFindBlockersPrompt: 'Определи блокирующие проблемы в переданном контексте проекта и предложи самый безопасный порядок их устранения.', aiPrioritizeTasks: 'Расставить приоритеты 10 задач', aiPrioritizeTasksPrompt: 'Расставь приоритеты для переданных 10 задач и объясни порядок с учётом срочности, блокировок и влияния на доход.', aiActionWhatNext: 'Что мне делать дальше?', aiActionFindBlockers: 'Найти блокирующие проблемы', aiActionPrioritizeTasks: 'Расставить приоритеты 10 задач' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], aiCenterActionTranslations[language]))

const aiProjectIssueTranslations = {
  en: { projectIssueAiNotConfigured: 'AI Center requires OpenAI API billing and a backend-only API key before live responses can work.' },
  he: { projectIssueAiNotConfigured: 'מרכז AI דורש חיוב OpenAI ומפתח API בשרת בלבד לפני שניתן לקבל תשובות חיות.' },
  ar: { projectIssueAiNotConfigured: 'يتطلب مركز AI فوترة OpenAI ومفتاح API في الخادم فقط قبل تشغيل الردود الحية.' },
  ru: { projectIssueAiNotConfigured: 'Для живых ответов AI-центру нужны биллинг OpenAI и API-ключ только на сервере.' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], aiProjectIssueTranslations[language]))

const projectCleanupTranslations = {
  en: { projectNextFive: 'Next 5 Tasks', projectBlockingIssues: 'Known Blocking Issues' },
  he: { projectNextFive: '5 המשימות הבאות', projectBlockingIssues: 'בעיות חוסמות ידועות', flow_Lead: 'ליד', flow_CRM: 'CRM', flow_DemoSite: 'אתר דמו', flow_SalesPitch: "פיץ' מכירה", flow_Proposal: 'הצעת מחיר', flow_WhatsApp: 'WhatsApp', flow_Payment: 'תשלום', flow_RealWebsite: 'אתר אמיתי', flow_Deployment: 'העלאה לאוויר', flow_CustomerSupport: 'תמיכת לקוח' },
  ar: { projectNextFive: 'المهام الخمس التالية', projectBlockingIssues: 'المشكلات الحاجبة المعروفة' },
  ru: { projectNextFive: 'Следующие 5 задач', projectBlockingIssues: 'Известные блокирующие проблемы' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], projectCleanupTranslations[language]))

const realWebsiteBuilderTranslations = {
  en: { realWebsiteBuilder: 'Real Website Builder', buildRealWebsite: 'Build Real Website', rwbSubtitle: 'Create and manage production-ready customer website projects.', rwbCreate: 'Create Website', rwbSaveDraft: 'Save Draft', rwbLoadDraft: 'Load Draft', rwbReset: 'Reset', rwbFullPreview: 'Open Full Preview', rwbMarkReady: 'Mark Ready for Publish', rwbCustomerDetails: 'Customer details', rwbLivePreview: 'Live preview', rwbProjects: 'Website projects', rwbEdit: 'Edit', rwbPreview: 'Preview', rwbNoProjects: 'No saved website projects yet.', rwbSaved: 'Website project saved.', rwbCreated: 'Website generated.', rwbBusinessRequired: 'Business name is required.', rwbTemplateModern: 'Modern Service Business', rwbTemplatePremium: 'Premium Local Business', rwbTemplateOffice: 'Professional Office', rwbField_businessName: 'Business name', rwbField_businessType: 'Business type', rwbField_country: 'Country', rwbField_city: 'City', rwbField_language: 'Website language', rwbField_phone: 'Phone', rwbField_whatsapp: 'WhatsApp', rwbField_email: 'Email', rwbField_address: 'Address', rwbField_currentWebsite: 'Current website', rwbField_logoUrl: 'Logo URL', rwbField_primaryColor: 'Primary color', rwbField_secondaryColor: 'Secondary color', rwbField_shortDescription: 'Short business description', rwbField_mainServices: 'Main services', rwbField_preferredTemplate: 'Preferred template', 'rwbStatus_draft': 'Draft', 'rwbStatus_in-progress': 'In Progress', 'rwbStatus_client-review': 'Client Review', 'rwbStatus_ready-to-publish': 'Ready to Publish', 'rwbStatus_published': 'Published' },
  he: { realWebsiteBuilder: 'בונה אתרים אמיתיים', buildRealWebsite: 'בניית אתר אמיתי', rwbSubtitle: 'יצירה וניהול של פרויקטי אתרים מוכנים ללקוחות.', rwbCreate: 'יצירת אתר', rwbSaveDraft: 'שמירת טיוטה', rwbLoadDraft: 'טעינת טיוטה', rwbReset: 'איפוס', rwbFullPreview: 'פתיחת תצוגה מלאה', rwbMarkReady: 'סימון כמוכן לפרסום', rwbCustomerDetails: 'פרטי הלקוח', rwbLivePreview: 'תצוגה מקדימה חיה', rwbProjects: 'פרויקטי אתרים', rwbEdit: 'עריכה', rwbPreview: 'תצוגה', rwbNoProjects: 'אין עדיין פרויקטי אתרים שמורים.', rwbSaved: 'פרויקט האתר נשמר.', rwbCreated: 'האתר נוצר.', rwbBusinessRequired: 'שם העסק הוא שדה חובה.', rwbTemplateModern: 'עסק שירותים מודרני', rwbTemplatePremium: 'עסק מקומי פרימיום', rwbTemplateOffice: 'משרד מקצועי', rwbField_businessName: 'שם העסק', rwbField_businessType: 'סוג העסק', rwbField_country: 'מדינה', rwbField_city: 'עיר', rwbField_language: 'שפת האתר', rwbField_phone: 'טלפון', rwbField_whatsapp: 'WhatsApp', rwbField_email: 'אימייל', rwbField_address: 'כתובת', rwbField_currentWebsite: 'אתר נוכחי', rwbField_logoUrl: 'כתובת לוגו', rwbField_primaryColor: 'צבע ראשי', rwbField_secondaryColor: 'צבע משני', rwbField_shortDescription: 'תיאור קצר של העסק', rwbField_mainServices: 'שירותים עיקריים', rwbField_preferredTemplate: 'תבנית מועדפת', 'rwbStatus_draft': 'טיוטה', 'rwbStatus_in-progress': 'בתהליך', 'rwbStatus_client-review': 'בדיקת לקוח', 'rwbStatus_ready-to-publish': 'מוכן לפרסום', 'rwbStatus_published': 'פורסם' },
  ar: { realWebsiteBuilder: 'منشئ المواقع الحقيقية', buildRealWebsite: 'إنشاء موقع حقيقي', rwbSubtitle: 'إنشاء وإدارة مشاريع مواقع جاهزة للعملاء.', rwbCreate: 'إنشاء الموقع', rwbSaveDraft: 'حفظ المسودة', rwbLoadDraft: 'تحميل المسودة', rwbReset: 'إعادة ضبط', rwbFullPreview: 'فتح المعاينة الكاملة', rwbMarkReady: 'تحديد كجاهز للنشر', rwbCustomerDetails: 'بيانات العميل', rwbLivePreview: 'معاينة مباشرة', rwbProjects: 'مشاريع المواقع', rwbEdit: 'تعديل', rwbPreview: 'معاينة', rwbNoProjects: 'لا توجد مشاريع مواقع محفوظة.', rwbSaved: 'تم حفظ مشروع الموقع.', rwbCreated: 'تم إنشاء الموقع.', rwbBusinessRequired: 'اسم النشاط مطلوب.', rwbTemplateModern: 'نشاط خدمات حديث', rwbTemplatePremium: 'نشاط محلي مميز', rwbTemplateOffice: 'مكتب مهني', rwbField_businessName: 'اسم النشاط', rwbField_businessType: 'نوع النشاط', rwbField_country: 'الدولة', rwbField_city: 'المدينة', rwbField_language: 'لغة الموقع', rwbField_phone: 'الهاتف', rwbField_whatsapp: 'WhatsApp', rwbField_email: 'البريد الإلكتروني', rwbField_address: 'العنوان', rwbField_currentWebsite: 'الموقع الحالي', rwbField_logoUrl: 'رابط الشعار', rwbField_primaryColor: 'اللون الأساسي', rwbField_secondaryColor: 'اللون الثانوي', rwbField_shortDescription: 'وصف مختصر للنشاط', rwbField_mainServices: 'الخدمات الرئيسية', rwbField_preferredTemplate: 'القالب المفضل', 'rwbStatus_draft': 'مسودة', 'rwbStatus_in-progress': 'قيد التنفيذ', 'rwbStatus_client-review': 'مراجعة العميل', 'rwbStatus_ready-to-publish': 'جاهز للنشر', 'rwbStatus_published': 'منشور' },
  ru: { realWebsiteBuilder: 'Конструктор реальных сайтов', buildRealWebsite: 'Создать реальный сайт', rwbSubtitle: 'Создание и управление рабочими сайтами клиентов.', rwbCreate: 'Создать сайт', rwbSaveDraft: 'Сохранить черновик', rwbLoadDraft: 'Загрузить черновик', rwbReset: 'Сбросить', rwbFullPreview: 'Открыть полный просмотр', rwbMarkReady: 'Готово к публикации', rwbCustomerDetails: 'Данные клиента', rwbLivePreview: 'Предпросмотр', rwbProjects: 'Проекты сайтов', rwbEdit: 'Изменить', rwbPreview: 'Просмотр', rwbNoProjects: 'Сохранённых проектов пока нет.', rwbSaved: 'Проект сайта сохранён.', rwbCreated: 'Сайт создан.', rwbBusinessRequired: 'Название компании обязательно.', rwbTemplateModern: 'Современный сервисный бизнес', rwbTemplatePremium: 'Премиальный местный бизнес', rwbTemplateOffice: 'Профессиональный офис', rwbField_businessName: 'Название компании', rwbField_businessType: 'Тип бизнеса', rwbField_country: 'Страна', rwbField_city: 'Город', rwbField_language: 'Язык сайта', rwbField_phone: 'Телефон', rwbField_whatsapp: 'WhatsApp', rwbField_email: 'Email', rwbField_address: 'Адрес', rwbField_currentWebsite: 'Текущий сайт', rwbField_logoUrl: 'URL логотипа', rwbField_primaryColor: 'Основной цвет', rwbField_secondaryColor: 'Дополнительный цвет', rwbField_shortDescription: 'Краткое описание бизнеса', rwbField_mainServices: 'Основные услуги', rwbField_preferredTemplate: 'Предпочтительный шаблон', 'rwbStatus_draft': 'Черновик', 'rwbStatus_in-progress': 'В работе', 'rwbStatus_client-review': 'Проверка клиентом', 'rwbStatus_ready-to-publish': 'Готов к публикации', 'rwbStatus_published': 'Опубликован' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], realWebsiteBuilderTranslations[language]))

const premiumWebsiteTranslations = {
  en: { rwbField_heroImageUrl: 'Hero image URL', rwbField_galleryImageUrls: 'Gallery image URLs', rwbCompareTemplates: 'Compare premium templates', rwbTemplateModernDescription: 'Bold split hero and conversion-first service cards.', rwbTemplatePremiumDescription: 'Editorial image hero, elegant type, and refined spacing.', rwbTemplateOfficeDescription: 'Structured trust layout for professional offices.', rwbViewport_desktop: 'Desktop', rwbViewport_tablet: 'Tablet', rwbViewport_mobile: 'Mobile', rwbReadinessError: 'Not ready: add a business name, phone or email, at least three services, and complete website content.' },
  he: { rwbField_heroImageUrl: 'כתובת תמונת גיבור', rwbField_galleryImageUrls: 'כתובות תמונות גלריה', rwbCompareTemplates: 'השוואת תבניות פרימיום', rwbTemplateModernDescription: 'גיבור מפוצל ובולט וכרטיסי שירות ממוקדי המרה.', rwbTemplatePremiumDescription: 'גיבור תמונה עריכתי, טיפוגרפיה אלגנטית ומרווחים מעודנים.', rwbTemplateOfficeDescription: 'מבנה אמון מסודר למשרדים מקצועיים.', rwbViewport_desktop: 'מחשב', rwbViewport_tablet: 'טאבלט', rwbViewport_mobile: 'נייד', rwbReadinessError: 'האתר אינו מוכן: יש להוסיף שם עסק, טלפון או אימייל, לפחות שלושה שירותים ותוכן אתר מלא.' },
  ar: { rwbField_heroImageUrl: 'رابط صورة الواجهة', rwbField_galleryImageUrls: 'روابط صور المعرض', rwbCompareTemplates: 'مقارنة القوالب المميزة', rwbTemplateModernDescription: 'واجهة منقسمة جريئة وبطاقات خدمات تركز على التحويل.', rwbTemplatePremiumDescription: 'واجهة صورية تحريرية وخطوط أنيقة ومساحات راقية.', rwbTemplateOfficeDescription: 'تصميم ثقة منظم للمكاتب المهنية.', rwbViewport_desktop: 'سطح المكتب', rwbViewport_tablet: 'جهاز لوحي', rwbViewport_mobile: 'هاتف', rwbReadinessError: 'الموقع غير جاهز: أضف اسم النشاط وهاتفًا أو بريدًا وثلاث خدمات على الأقل ومحتوى مكتملًا.' },
  ru: { rwbField_heroImageUrl: 'URL главного изображения', rwbField_galleryImageUrls: 'URL изображений галереи', rwbCompareTemplates: 'Сравнить премиальные шаблоны', rwbTemplateModernDescription: 'Смелый разделённый экран и сервисные карточки для конверсии.', rwbTemplatePremiumDescription: 'Редакционный фотоэкран, элегантный шрифт и утончённые интервалы.', rwbTemplateOfficeDescription: 'Структурный доверительный дизайн для профессиональных офисов.', rwbViewport_desktop: 'Компьютер', rwbViewport_tablet: 'Планшет', rwbViewport_mobile: 'Телефон', rwbReadinessError: 'Сайт не готов: добавьте название, телефон или email, минимум три услуги и полный контент.' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], premiumWebsiteTranslations[language]))

const commandCenterNavTranslations = {
  en: { commandCenter: 'Command Center', salesCenterNav: 'Sales Center', websiteBuilderNav: 'Website Builder', developmentNav: 'Development', documentsNav: 'Documents', usersNav: 'Users', integrationsNav: 'Integrations', 'sales-center': 'Sales Center', 'website-builder': 'Website Builder', users: 'Users', integrations: 'Integrations', salesCenterPlaceholder: 'Open a lead in BS Finder to use its personalized Sales Center.', websiteBuilderPlaceholder: 'Open a lead in BS Finder to create or preview its demo website.', usersPlaceholder: 'User management and role assignments are not connected yet.', integrationsPlaceholder: 'External integration management is not connected yet.' },
  he: { commandCenter: 'מרכז שליטה', salesCenterNav: 'מרכז מכירות', websiteBuilderNav: 'בונה אתרים', developmentNav: 'פיתוח', documentsNav: 'מסמכים', usersNav: 'משתמשים', integrationsNav: 'חיבורים', 'sales-center': 'מרכז מכירות', 'website-builder': 'בונה אתרים', users: 'משתמשים', integrations: 'חיבורים', salesCenterPlaceholder: 'פתחו ליד ב-BS Finder כדי להשתמש במרכז המכירות האישי.', websiteBuilderPlaceholder: 'פתחו ליד ב-BS Finder כדי ליצור או להציג אתר דמו.', usersPlaceholder: 'ניהול משתמשים ותפקידים עדיין אינו מחובר.', integrationsPlaceholder: 'ניהול חיבורים חיצוניים עדיין אינו מחובר.' },
  ar: { commandCenter: 'مركز القيادة', salesCenterNav: 'مركز المبيعات', websiteBuilderNav: 'منشئ المواقع', developmentNav: 'التطوير', documentsNav: 'المستندات', usersNav: 'المستخدمون', integrationsNav: 'التكاملات', 'sales-center': 'مركز المبيعات', 'website-builder': 'منشئ المواقع', users: 'المستخدمون', integrations: 'التكاملات', salesCenterPlaceholder: 'افتح عميلاً في BS Finder لاستخدام مركز المبيعات المخصص.', websiteBuilderPlaceholder: 'افتح عميلاً في BS Finder لإنشاء أو معاينة موقعه التجريبي.', usersPlaceholder: 'إدارة المستخدمين والأدوار غير متصلة بعد.', integrationsPlaceholder: 'إدارة التكاملات الخارجية غير متصلة بعد.' },
  ru: { commandCenter: 'Центр управления', salesCenterNav: 'Центр продаж', websiteBuilderNav: 'Конструктор сайтов', developmentNav: 'Разработка', documentsNav: 'Документы', usersNav: 'Пользователи', integrationsNav: 'Интеграции', 'sales-center': 'Центр продаж', 'website-builder': 'Конструктор сайтов', users: 'Пользователи', integrations: 'Интеграции', salesCenterPlaceholder: 'Откройте лид в BS Finder, чтобы использовать его Центр продаж.', websiteBuilderPlaceholder: 'Откройте лид в BS Finder, чтобы создать или просмотреть демо-сайт.', usersPlaceholder: 'Управление пользователями и ролями пока не подключено.', integrationsPlaceholder: 'Управление внешними интеграциями пока не подключено.' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], commandCenterNavTranslations[language]))

const navigationHierarchyTranslations = {
  en: { businesses: 'Businesses', businessesDescription: 'Operating businesses managed through Business OS.', primaryRevenueBusiness: 'Primary revenue business', bsFinderDescription: 'Lead discovery, sales, demo sites, proposals, follow-up, and customer website delivery.', openBusinessWorkspace: 'Open business workspace', technicalNameBsHunter: 'Current technical name: BS Hunter', bsFinderWorkspaceDescription: 'Operate the complete lead-to-customer workflow from one focused workspace.', backToBusinesses: 'Businesses', technicalName: 'Technical name', workspaceStatus: 'Status', activePartial: 'Active · partially operational', openModule: 'Open module', leadDiscovery: 'Lead Discovery', leadDiscoveryDescription: 'Find, import, qualify, and manage real leads.', leadCrmDescription: 'Open the current CRM view and lead-level controls.', sales: 'Sales', salesWorkspaceDescription: 'Access lead outreach, Sales Center, WhatsApp, and follow-up actions.', proposalGenerator: 'Proposal Generator', proposalWorkspaceDescription: 'Open BS Finder leads and create a personalized proposal.', demoWebsiteBuilder: 'Demo Website Builder', demoBuilderWorkspaceDescription: 'Create and preview a demo from a selected lead.', realBuilderWorkspaceDescription: 'Create and manage customer website projects.', websitesAssets: 'Websites & Assets', websitesAssetsDescription: 'Manage reusable sites, customer websites, templates, and digital assets.', available: 'Available', planned: 'Planned', openAsset: 'Open asset', bsFundsAssetDescription: 'Existing reusable finance website asset and preserved project shell.', demoWebsitesAsset: 'Demo Websites', demoWebsitesAssetDescription: 'Open BS Finder to create and review lead demo sites.', customerWebsitesAsset: 'Customer Websites', customerWebsitesAssetDescription: 'Open the Real Website Builder project workspace.', templatesAsset: 'Templates', templatesAssetDescription: 'A dedicated template library is not connected yet.', landingPagesAsset: 'Landing Pages', landingPagesAssetDescription: 'Landing page management is planned.', archivedWebsitesAsset: 'Archived Websites', archivedWebsitesAssetDescription: 'Website archiving is not connected yet.', analytics: 'Analytics', analyticsPlaceholder: 'Business analytics will appear here when authoritative data sources are connected.', usersPermissions: 'Users & Permissions', salesModulePlaceholder: 'Global sales reporting is not connected yet. Open BS Finder for current lead sales actions.' },
  he: { businesses: 'עסקים', businessesDescription: 'עסקים פעילים המנוהלים דרך Business OS.', primaryRevenueBusiness: 'העסק המרכזי ליצירת הכנסות', bsFinderDescription: 'איתור לידים, מכירות, אתרי דמו, הצעות, מעקב ומסירת אתרי לקוחות.', openBusinessWorkspace: 'פתיחת סביבת העסק', technicalNameBsHunter: 'שם טכני נוכחי: BS Hunter', bsFinderWorkspaceDescription: 'ניהול תהליך מלא מליד ללקוח מתוך סביבת עבודה ממוקדת.', backToBusinesses: 'עסקים', technicalName: 'שם טכני', workspaceStatus: 'סטטוס', activePartial: 'פעיל · תפעול חלקי', openModule: 'פתיחת מודול', leadDiscovery: 'איתור לידים', leadDiscoveryDescription: 'חיפוש, ייבוא, דירוג וניהול לידים אמיתיים.', leadCrmDescription: 'פתיחת תצוגת ה-CRM ובקרות הליד הקיימות.', sales: 'מכירות', salesWorkspaceDescription: 'גישה לפנייה ללידים, מרכז המכירות, WhatsApp ומעקבים.', proposalGenerator: 'מחולל הצעות מחיר', proposalWorkspaceDescription: 'פתיחת לידים ב-BS Finder ויצירת הצעה אישית.', demoWebsiteBuilder: 'בונה אתרי דמו', demoBuilderWorkspaceDescription: 'יצירה ותצוגה של אתר דמו מליד שנבחר.', realBuilderWorkspaceDescription: 'יצירה וניהול של פרויקטי אתרים ללקוחות.', websitesAssets: 'אתרים ונכסים', websitesAssetsDescription: 'ניהול אתרים לשימוש חוזר, אתרי לקוחות, תבניות ונכסים דיגיטליים.', available: 'זמין', planned: 'מתוכנן', openAsset: 'פתיחת נכס', bsFundsAssetDescription: 'נכס אתר פיננסי קיים לשימוש חוזר ומעטפת פרויקט שמורה.', demoWebsitesAsset: 'אתרי דמו', demoWebsitesAssetDescription: 'פתיחת BS Finder ליצירה ולבדיקה של אתרי דמו ללידים.', customerWebsitesAsset: 'אתרי לקוחות', customerWebsitesAssetDescription: 'פתיחת סביבת פרויקטי בונה האתרים האמיתי.', templatesAsset: 'תבניות', templatesAssetDescription: 'ספריית תבניות ייעודית עדיין אינה מחוברת.', landingPagesAsset: 'דפי נחיתה', landingPagesAssetDescription: 'ניהול דפי נחיתה מתוכנן.', archivedWebsitesAsset: 'אתרים בארכיון', archivedWebsitesAssetDescription: 'ארכוב אתרים עדיין אינו מחובר.', analytics: 'אנליטיקה', analyticsPlaceholder: 'נתוני אנליטיקה עסקיים יופיעו כאן לאחר חיבור מקורות מידע מוסמכים.', usersPermissions: 'משתמשים והרשאות', salesModulePlaceholder: 'דוחות מכירה גלובליים עדיין אינם מחוברים. פתחו את BS Finder לפעולות המכירה הקיימות.' },
  ar: { businesses: 'الأعمال', businessesDescription: 'الأعمال التشغيلية المُدارة عبر Business OS.', primaryRevenueBusiness: 'نشاط الإيرادات الرئيسي', bsFinderDescription: 'اكتشاف العملاء والمبيعات والمواقع التجريبية والعروض والمتابعة وتسليم مواقع العملاء.', openBusinessWorkspace: 'فتح مساحة العمل', technicalNameBsHunter: 'الاسم التقني الحالي: BS Hunter', bsFinderWorkspaceDescription: 'إدارة مسار العميل الكامل من مساحة واحدة.', backToBusinesses: 'الأعمال', technicalName: 'الاسم التقني', workspaceStatus: 'الحالة', activePartial: 'نشط · تشغيل جزئي', openModule: 'فتح الوحدة', leadDiscovery: 'اكتشاف العملاء', leadDiscoveryDescription: 'البحث عن العملاء واستيرادهم وتأهيلهم وإدارتهم.', leadCrmDescription: 'فتح CRM الحالي وضوابط العملاء.', sales: 'المبيعات', salesWorkspaceDescription: 'الوصول إلى التواصل ومركز المبيعات وWhatsApp والمتابعة.', proposalGenerator: 'منشئ العروض', proposalWorkspaceDescription: 'فتح العملاء وإنشاء عرض مخصص.', demoWebsiteBuilder: 'منشئ المواقع التجريبية', demoBuilderWorkspaceDescription: 'إنشاء ومعاينة موقع تجريبي لعميل محدد.', realBuilderWorkspaceDescription: 'إنشاء وإدارة مشاريع مواقع العملاء.', websitesAssets: 'المواقع والأصول', websitesAssetsDescription: 'إدارة المواقع القابلة لإعادة الاستخدام ومواقع العملاء والقوالب والأصول.', available: 'متاح', planned: 'مخطط', openAsset: 'فتح الأصل', bsFundsAssetDescription: 'أصل موقع مالي قائم وقابل لإعادة الاستخدام.', demoWebsitesAsset: 'المواقع التجريبية', demoWebsitesAssetDescription: 'فتح BS Finder لإنشاء ومراجعة مواقع العملاء التجريبية.', customerWebsitesAsset: 'مواقع العملاء', customerWebsitesAssetDescription: 'فتح مساحة منشئ المواقع الحقيقية.', templatesAsset: 'القوالب', templatesAssetDescription: 'مكتبة القوالب غير متصلة بعد.', landingPagesAsset: 'صفحات الهبوط', landingPagesAssetDescription: 'إدارة صفحات الهبوط مخططة.', archivedWebsitesAsset: 'المواقع المؤرشفة', archivedWebsitesAssetDescription: 'الأرشفة غير متصلة بعد.', analytics: 'التحليلات', analyticsPlaceholder: 'ستظهر تحليلات الأعمال عند ربط مصادر بيانات موثوقة.', usersPermissions: 'المستخدمون والصلاحيات', salesModulePlaceholder: 'تقارير المبيعات العامة غير متصلة بعد. افتح BS Finder لإجراءات المبيعات الحالية.' },
  ru: { businesses: 'Бизнесы', businessesDescription: 'Операционные бизнесы под управлением Business OS.', primaryRevenueBusiness: 'Основной доходный бизнес', bsFinderDescription: 'Поиск лидов, продажи, демо-сайты, предложения, контакты и сайты клиентов.', openBusinessWorkspace: 'Открыть рабочую область', technicalNameBsHunter: 'Текущее техническое имя: BS Hunter', bsFinderWorkspaceDescription: 'Управление всем циклом от лида до клиента в одной области.', backToBusinesses: 'Бизнесы', technicalName: 'Техническое имя', workspaceStatus: 'Статус', activePartial: 'Активен · частично работает', openModule: 'Открыть модуль', leadDiscovery: 'Поиск лидов', leadDiscoveryDescription: 'Поиск, импорт, оценка и управление реальными лидами.', leadCrmDescription: 'Открыть текущий CRM и элементы управления лидами.', sales: 'Продажи', salesWorkspaceDescription: 'Доступ к коммуникациям, Центру продаж, WhatsApp и контактам.', proposalGenerator: 'Генератор предложений', proposalWorkspaceDescription: 'Открыть лиды BS Finder и создать персональное предложение.', demoWebsiteBuilder: 'Конструктор демо-сайтов', demoBuilderWorkspaceDescription: 'Создать и просмотреть демо для выбранного лида.', realBuilderWorkspaceDescription: 'Создание и управление проектами сайтов клиентов.', websitesAssets: 'Сайты и активы', websitesAssetsDescription: 'Управление повторно используемыми сайтами, клиентскими сайтами, шаблонами и активами.', available: 'Доступно', planned: 'Запланировано', openAsset: 'Открыть актив', bsFundsAssetDescription: 'Существующий повторно используемый финансовый веб-актив.', demoWebsitesAsset: 'Демо-сайты', demoWebsitesAssetDescription: 'Открыть BS Finder для создания и проверки демо-сайтов.', customerWebsitesAsset: 'Сайты клиентов', customerWebsitesAssetDescription: 'Открыть рабочую область реального конструктора сайтов.', templatesAsset: 'Шаблоны', templatesAssetDescription: 'Отдельная библиотека шаблонов пока не подключена.', landingPagesAsset: 'Лендинги', landingPagesAssetDescription: 'Управление лендингами запланировано.', archivedWebsitesAsset: 'Архивные сайты', archivedWebsitesAssetDescription: 'Архив сайтов пока не подключён.', analytics: 'Аналитика', analyticsPlaceholder: 'Бизнес-аналитика появится после подключения авторитетных источников данных.', usersPermissions: 'Пользователи и права', salesModulePlaceholder: 'Общая отчётность продаж пока не подключена. Откройте BS Finder для текущих действий.' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], navigationHierarchyTranslations[language]))

const navigationCleanupTranslations = {
  en: { openBsHunter: 'Open BS Finder', emptyDashboardMessage: 'Open BS Finder to discover businesses and start building your pipeline.', priorityOpenHunterAction: 'Open BS Finder and load or find leads.', revenueGeneratingBusiness: 'Revenue-generating business', currentBusinessTask: 'Current task', protectSourceTask: 'Protect source and inspect repositories', openBusiness: 'Open Business' },
  he: { openBsHunter: 'פתיחת BS Finder', emptyDashboardMessage: 'פתחו את BS Finder כדי למצוא עסקים ולהתחיל לבנות תהליך מכירה.', priorityOpenHunterAction: 'פתחו את BS Finder וטענו או חפשו לידים.', revenueGeneratingBusiness: 'עסק ליצירת הכנסות', currentBusinessTask: 'משימה נוכחית', protectSourceTask: 'הגנת קוד המקור ובדיקת המאגרים', openBusiness: 'פתיחת העסק' },
  ar: { openBsHunter: 'فتح BS Finder', emptyDashboardMessage: 'افتح BS Finder لاكتشاف الأنشطة وبناء مسار المبيعات.', priorityOpenHunterAction: 'افتح BS Finder وحمّل العملاء أو ابحث عنهم.', revenueGeneratingBusiness: 'نشاط مولّد للإيرادات', currentBusinessTask: 'المهمة الحالية', protectSourceTask: 'حماية المصدر وفحص المستودعات', openBusiness: 'فتح النشاط' },
  ru: { openBsHunter: 'Открыть BS Finder', emptyDashboardMessage: 'Откройте BS Finder, чтобы найти компании и начать строить воронку.', priorityOpenHunterAction: 'Откройте BS Finder и загрузите или найдите лиды.', revenueGeneratingBusiness: 'Доходный бизнес', currentBusinessTask: 'Текущая задача', protectSourceTask: 'Защитить исходники и проверить репозитории', openBusiness: 'Открыть бизнес' },
}

Object.keys(translations).forEach((language) => Object.assign(translations[language], navigationCleanupTranslations[language]))

export const DEFAULT_LANGUAGE = 'en'
