// Professional local-first owner command center backed by existing leads, CRM, tasks, and verified project facts.
import { useEffect, useMemo, useState } from 'react'
import { useLanguage } from '../../context/LanguageContext'
import { subscribeToCrmChanges } from '../LeadCRM/crmStorage'
import { subscribeToLeadActionChanges } from '../LeadCRM/leadActionStorage'
import { localizeTaskContent } from '../Projects/projectData'
import { DASHBOARD_FILTERS, getLeadDashboardData, isDemoLead } from './dashboardFilters'
import { commandDocuments, COMMAND_CENTER_UPDATED, developmentFacts, ecosystemProjects, knownCommandIssues, loadIdeas, saveIdea } from './commandCenterData'
import { loadTasks, saveTasks, sortTasks, subscribeToTaskChanges } from './taskStorage'

const COPY = {
  en: { title: 'Business OS Command Center', phase: 'Structure protection & pre-revenue operations', status: 'System stable · local mode', updated: 'Last updated', focus: 'Focus Mode', exitFocus: 'Exit Focus', mission: 'CURRENT MISSION', project: 'Current project', why: 'Why it matters', revenue: 'Revenue impact', priority: 'Priority', blocking: 'Blocking', assigned: 'Assigned to', progress: 'Progress', start: 'Start', complete: 'Mark Complete', openProject: 'Open Project', nextAction: 'Next immediate action', idea: 'Quick idea capture', ideaTitle: 'Idea title', related: 'Related project', saveIdea: 'Save idea', saved: 'Idea saved locally.', overview: 'Business overview', local: 'Local', unavailable: 'Unavailable', notConnected: 'Not connected', revenueCard: 'Revenue', leads: 'Leads', sales: 'Sales', activeProjects: 'Active Projects', openTasks: 'Open Tasks', blockingIssues: 'Blocking Issues', agents: 'Active AI Agents', backup: 'Last Backup', projects: 'Projects', development: 'Development Console', documents: 'Document Center', nextTasks: 'Next 10 Tasks', issues: 'Known Issues', ai: 'AI Center Summary', activeAgents: 'Active agents', idleAgents: 'Idle agents', failedAgents: 'Failed agents', queued: 'Queued work', lastAgent: 'Last completed agent task', assignedProject: 'Assigned project', view: 'View', exists: 'Exists', purpose: 'Purpose', currentTask: 'Current task', nextTask: 'Next task', blockers: 'Known blockers', repository: 'Repository status', lastUpdate: 'Last update', technical: 'Technical name', open: 'Open Project', task: 'Task', taskStatus: 'Status', yes: 'Yes', no: 'No', noMission: 'No incomplete local task is available.', noIdeas: 'No ideas captured yet.', themeLight: 'Light', themeDark: 'Dark', critical: 'Critical', high: 'High', medium: 'Medium', low: 'Low' },
  he: { title: 'מרכז השליטה של Business OS', phase: 'הגנת מבנה ותפעול לפני הכנסות', status: 'המערכת יציבה · מצב מקומי', updated: 'עודכן לאחרונה', focus: 'מצב מיקוד', exitFocus: 'יציאה ממיקוד', mission: 'המשימה הנוכחית', project: 'פרויקט נוכחי', why: 'למה זה חשוב', revenue: 'השפעה על הכנסות', priority: 'עדיפות', blocking: 'חוסם', assigned: 'אחראי', progress: 'התקדמות', start: 'התחלה', complete: 'סימון כהושלם', openProject: 'פתיחת פרויקט', nextAction: 'הפעולה המיידית הבאה', idea: 'לכידת רעיון מהירה', ideaTitle: 'כותרת הרעיון', related: 'פרויקט קשור', saveIdea: 'שמירת רעיון', saved: 'הרעיון נשמר מקומית.', overview: 'סקירת העסק', local: 'מקומי', unavailable: 'לא זמין', notConnected: 'לא מחובר', revenueCard: 'הכנסות', leads: 'לידים', sales: 'מכירות', activeProjects: 'פרויקטים פעילים', openTasks: 'משימות פתוחות', blockingIssues: 'בעיות חוסמות', agents: 'סוכני AI פעילים', backup: 'גיבוי אחרון', projects: 'פרויקטים', development: 'מסוף פיתוח', documents: 'מרכז מסמכים', nextTasks: '10 המשימות הבאות', issues: 'בעיות ידועות', ai: 'סיכום מרכז AI', activeAgents: 'סוכנים פעילים', idleAgents: 'סוכנים לא פעילים', failedAgents: 'סוכנים שנכשלו', queued: 'עבודה בתור', lastAgent: 'משימת סוכן אחרונה', assignedProject: 'פרויקט משויך', view: 'צפייה', exists: 'קיים', purpose: 'מטרה', currentTask: 'משימה נוכחית', nextTask: 'המשימה הבאה', blockers: 'חסמים ידועים', repository: 'מצב מאגר', lastUpdate: 'עדכון אחרון', technical: 'שם טכני', open: 'פתיחת פרויקט', task: 'משימה', taskStatus: 'סטטוס', yes: 'כן', no: 'לא', noMission: 'אין משימה מקומית פתוחה.', noIdeas: 'עדיין לא נשמרו רעיונות.', themeLight: 'בהיר', themeDark: 'כהה', critical: 'קריטי', high: 'גבוה', medium: 'בינוני', low: 'נמוך' },
}

const OWNER_COPY = {
  en: { revenueOverview: 'Revenue & operations', revenueToday: 'Revenue Today', revenueMonth: 'Revenue This Month', expectedRevenue: 'Expected Revenue', newLeadsToday: 'New Leads Today', activeDeals: 'Active Deals', followUpsDue: 'Follow-ups Due', demosWaiting: 'Demo Websites Waiting', tasksDueToday: 'Tasks Due Today', businessHealth: 'Business Health', quickActions: 'Quick Actions', leadPipeline: 'Lead pipeline', taskOperations: 'Task operations', aiConnection: 'AI connection', localSystem: 'Local system', healthy: 'Available', needsAttention: 'Needs attention', openBsFinder: 'Open BS Finder', openAssets: 'Websites & Assets', openCrm: 'Open CRM', openTasks: 'Open Tasks', openAi: 'Open AI Center', openDevelopment: 'Open Development', openDocuments: 'Open Documents' },
  he: { revenueOverview: 'הכנסות ותפעול', revenueToday: 'הכנסות היום', revenueMonth: 'הכנסות החודש', expectedRevenue: 'הכנסות צפויות', newLeadsToday: 'לידים חדשים היום', activeDeals: 'עסקאות פעילות', followUpsDue: 'מעקבים לביצוע', demosWaiting: 'אתרי דמו ממתינים', tasksDueToday: 'משימות להיום', businessHealth: 'בריאות העסק', quickActions: 'פעולות מהירות', leadPipeline: 'תהליך הלידים', taskOperations: 'תפעול משימות', aiConnection: 'חיבור AI', localSystem: 'מערכת מקומית', healthy: 'זמין', needsAttention: 'דורש טיפול', openBsFinder: 'פתיחת BS Finder', openAssets: 'אתרים ונכסים', openCrm: 'פתיחת CRM', openTasks: 'פתיחת משימות', openAi: 'פתיחת מרכז AI', openDevelopment: 'פתיחת פיתוח', openDocuments: 'פתיחת מסמכים' },
}

function taskProgress(task) { return task?.status === 'completed' ? 100 : task?.status === 'in-progress' ? 50 : 0 }
function projectProgress(tasks, categories) { const relevant = tasks.filter((task) => categories.includes(task.category)); if (!relevant.length) return null; const value = relevant.reduce((sum, task) => sum + taskProgress(task), 0); return Math.round(value / relevant.length) }
function taskScreen(task) { if (['BS Hunter', 'Lead Search', 'Demo Websites', 'Sales', 'CRM', 'Proposals', 'WhatsApp'].includes(task?.category)) return 'bs-hunter'; if (task?.category === 'BS Funds') return 'websites-assets'; if (task?.category === 'Real Website Builder') return 'real-website-builder'; return 'tasks' }

function IdeaCapture({ copy, compact = false }) {
  const [draft, setDraft] = useState({ title: '', project: 'Business OS', priority: 'important' }); const [ideas, setIdeas] = useState(loadIdeas); const [notice, setNotice] = useState('')
  function submit(event) { event.preventDefault(); if (!draft.title.trim()) return; setIdeas(saveIdea({ id: `idea-${Date.now()}`, ...draft, title: draft.title.trim(), createdAt: new Date().toISOString() })); setDraft((value) => ({ ...value, title: '' })); setNotice(copy.saved) }
  return <section className={`command-ideas ${compact ? 'is-compact' : ''}`}><header><h2>{copy.idea}</h2><span>{copy.local}</span></header><form onSubmit={submit}><input aria-label={copy.ideaTitle} placeholder={copy.ideaTitle} value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /><select aria-label={copy.related} value={draft.project} onChange={(event) => setDraft({ ...draft, project: event.target.value })}>{ecosystemProjects.map((project) => <option key={project.id}>{project.name}</option>)}</select><select aria-label={copy.priority} value={draft.priority} onChange={(event) => setDraft({ ...draft, priority: event.target.value })}><option value="critical">{copy.critical}</option><option value="important">{copy.high}</option><option value="later">{copy.low}</option></select><button type="submit" disabled={!draft.title.trim()}>{copy.saveIdea}</button></form>{notice && <small>{notice}</small>}{!compact && <div className="command-ideas__list">{ideas.slice(0, 3).map((idea) => <article key={idea.id}><strong>{idea.title}</strong><span>{idea.project} · {idea.priority}</span></article>)}{!ideas.length && <p>{copy.noIdeas}</p>}</div>}</section>
}

export default function DashboardHome({ leads, onSelectFilter, onOpenScreen, theme, onToggleTheme }) {
  const { language, t } = useLanguage(); const copy = COPY[language] || COPY.en
  const [tasks, setTasks] = useState(loadTasks); const [focusMode, setFocusMode] = useState(false); const [revision, setRevision] = useState(0); const [selectedDocument, setSelectedDocument] = useState(commandDocuments[0])
  useEffect(() => subscribeToTaskChanges(() => setTasks(loadTasks())), [])
  useEffect(() => subscribeToCrmChanges(() => setRevision((value) => value + 1)), [])
  useEffect(() => subscribeToLeadActionChanges(() => setRevision((value) => value + 1)), [])

  const data = useMemo(() => {
    void revision
    const realLeads = leads.filter((lead) => !isDemoLead(lead)); const leadData = realLeads.map((lead) => ({ lead, ...getLeadDashboardData(lead) })); const ordered = sortTasks(tasks); const open = ordered.filter((task) => task.status !== 'completed'); const mission = open[0] || null
    const weighted = tasks.reduce((sum, task) => sum + taskProgress(task), 0); const overallProgress = tasks.length ? Math.round(weighted / tasks.length) : 0
    const today = new Date().toISOString().slice(0, 10)
    const newToday = realLeads.filter((lead) => String(lead.createdAt || lead.addedAt || lead.dateAdded || '').slice(0, 10) === today).length
    const activeDeals = leadData.filter(({ crm }) => ['contacted', 'whatsapp-sent', 'proposal-sent', 'negotiation'].includes(crm.status)).length
    const followUpsDue = leadData.filter(({ crm }) => crm.nextFollowUp && crm.nextFollowUp <= today && !['won', 'lost'].includes(crm.status)).length
    const tasksDueToday = open.filter((task) => String(task.dueDate || '').slice(0, 10) === today).length
    return { realLeads, leadData, open, mission, overallProgress, won: leadData.filter(({ crm }) => crm.status === 'won').length, blocking: open.filter((task) => task.isBlocking).length, hot: realLeads.filter((lead) => Number(lead.leadScore) >= 80).length, newToday, activeDeals, followUpsDue, tasksDueToday }
  }, [leads, revision, tasks])
  const ownerCopy = OWNER_COPY[language] || OWNER_COPY.en
  const mission = data.mission ? localizeTaskContent(data.mission, language, t) : null
  function updateMission(updates) { if (!data.mission) return; saveTasks(tasks.map((task) => task.id === data.mission.id ? { ...task, ...updates } : task)) }
  const projectCards = ecosystemProjects.filter((project) => project.id !== 'bs-funds').map((project) => ({ ...project, progress: projectProgress(tasks, project.categories) }))
  const ownerMetrics = [
    ['💰', ownerCopy.revenueToday, copy.notConnected, copy.unavailable, null], ['◷', ownerCopy.revenueMonth, copy.notConnected, copy.unavailable, null], ['↗', ownerCopy.expectedRevenue, copy.notConnected, copy.unavailable, null], ['◎', ownerCopy.newLeadsToday, data.newToday, copy.local, DASHBOARD_FILTERS.REAL_LEADS],
    ['◫', ownerCopy.activeDeals, data.activeDeals, copy.local, null], ['⌕', ownerCopy.followUpsDue, data.followUpsDue, copy.local, DASHBOARD_FILTERS.FOLLOW_UPS], ['◇', ownerCopy.demosWaiting, copy.unavailable, copy.notConnected, null], ['✓', ownerCopy.tasksDueToday, data.tasksDueToday, copy.local, null],
  ]
  const quickActions = [[ownerCopy.openBsFinder, 'bs-finder-workspace', '◎'], [ownerCopy.openAssets, 'websites-assets', '◇'], [ownerCopy.openCrm, 'crm', '◫'], [ownerCopy.openTasks, 'tasks', '✓'], [ownerCopy.openAi, 'ai-center', '✦'], [ownerCopy.openDevelopment, 'development', '⌘'], [ownerCopy.openDocuments, 'documents', '▤']]

  return <section className={`command-center ${focusMode ? 'is-focus' : ''}`} data-revision={revision}>
    <header className="command-header"><div><span>OWNER WORKSPACE</span><h1>{copy.title}</h1><p>{copy.phase}</p></div><dl><div><dt>{copy.progress}</dt><dd>{data.overallProgress}%</dd></div><div><dt>{copy.updated}</dt><dd>{COMMAND_CENTER_UPDATED}</dd></div><div><dt>System</dt><dd className="is-good">● {copy.status}</dd></div></dl><div className="command-header__actions"><button type="button" onClick={() => setFocusMode((value) => !value)}>{focusMode ? copy.exitFocus : copy.focus}</button><button type="button" className="theme-toggle" onClick={onToggleTheme} aria-label={theme === 'dark' ? copy.themeLight : copy.themeDark}>{theme === 'dark' ? '☀' : '◐'} {theme === 'dark' ? copy.themeLight : copy.themeDark}</button></div></header>

    {!focusMode && <section className="owner-revenue"><header><span>OWNER DASHBOARD</span><h2>{ownerCopy.revenueOverview}</h2></header><div className="owner-revenue__grid">{ownerMetrics.map(([icon, label, value, note, filter]) => <button type="button" key={label} disabled={!filter} onClick={() => filter && onSelectFilter(filter)}><i>{icon}</i><span>{label}</span><strong>{value}</strong><small>{note}</small></button>)}</div></section>}

    <article className="current-mission"><header><div><span>{copy.mission}</span><strong>{mission?.project || 'Business OS'}</strong></div><b className={mission?.priority === 'critical' ? 'is-critical' : 'is-important'}>{mission ? t(mission.priority === 'critical' ? 'taskCritical' : 'taskImportant') : '—'}</b></header>{mission ? <><div className="current-mission__body"><div><h2>{mission.title}</h2><p>{mission.description || copy.noMission}</p></div><dl><div><dt>{copy.revenue}</dt><dd>{mission.revenueImpact ? `$${Number(mission.revenueImpact).toLocaleString()}` : copy.unavailable}</dd></div><div><dt>{copy.blocking}</dt><dd>{mission.isBlocking ? copy.yes : copy.no}</dd></div><div><dt>{copy.assigned}</dt><dd>{mission.assignee || copy.unavailable}</dd></div></dl></div><div className="mission-progress"><span>{copy.progress}</span><div><i style={{ width: `${taskProgress(mission)}%` }} /></div><strong>{taskProgress(mission)}%</strong></div><div className="current-mission__actions"><button type="button" onClick={() => updateMission({ status: 'in-progress' })}>{copy.start}</button><button type="button" onClick={() => updateMission({ status: 'completed', priority: 'completed', completedAt: new Date().toISOString() })}>{copy.complete}</button><button type="button" onClick={() => onOpenScreen(taskScreen(mission))}>{copy.openProject}</button></div></> : <p>{copy.noMission}</p>}</article>

    {focusMode ? <div className="focus-workspace"><section><span>{copy.nextAction}</span><h2>{mission?.title || copy.noMission}</h2><p>{mission?.description || copy.noMission}</p><div className="focus-progress"><i style={{ width: `${taskProgress(mission)}%` }} /></div></section><IdeaCapture copy={copy} compact /></div> : <>
      <div className="owner-dashboard-row"><section className="command-section business-health"><header><div><span>STATUS</span><h2>{ownerCopy.businessHealth}</h2></div></header><div><article><span>●</span><p><strong>{ownerCopy.localSystem}</strong><small>{ownerCopy.healthy}</small></p></article><article><span>●</span><p><strong>{ownerCopy.leadPipeline}</strong><small>{data.realLeads.length} {copy.leads}</small></p></article><article className={data.blocking ? 'needs-attention' : ''}><span>●</span><p><strong>{ownerCopy.taskOperations}</strong><small>{data.blocking ? `${data.blocking} ${ownerCopy.needsAttention}` : ownerCopy.healthy}</small></p></article><article className="not-connected"><span>●</span><p><strong>{ownerCopy.aiConnection}</strong><small>{copy.notConnected}</small></p></article></div></section><section className="command-section quick-actions"><header><div><span>NAVIGATION</span><h2>{ownerCopy.quickActions}</h2></div></header><div>{quickActions.map(([label, screen, icon]) => <button type="button" key={screen} onClick={() => onOpenScreen(screen)}><span>{icon}</span>{label}</button>)}</div></section></div>
      <section className="command-section"><header><div><span>ECOSYSTEM</span><h2>{copy.projects}</h2></div></header><div className="command-projects">{projectCards.map((project) => <article key={project.id}><header><div><h3>{project.name}</h3><span>{copy.technical}: {project.technicalName}</span></div><strong>{project.progress === null ? '—' : `${project.progress}%`}</strong></header><p>{project.purpose}</p><dl><div><dt>{copy.taskStatus}</dt><dd>{project.status}</dd></div><div><dt>{copy.currentTask}</dt><dd>{project.currentTask}</dd></div><div><dt>{copy.nextTask}</dt><dd>{project.nextTask}</dd></div><div><dt>{copy.blockers}</dt><dd>{project.blockers.join(' · ')}</dd></div><div><dt>{copy.repository}</dt><dd>{project.repository}</dd></div><div><dt>{copy.lastUpdate}</dt><dd>{project.lastUpdate}</dd></div></dl><button type="button" onClick={() => onOpenScreen(project.screen)}>{copy.open}</button></article>)}</div></section>
      <div className="command-two-column"><section className="command-panel development-console"><header><h2>{copy.development}</h2><span>{copy.local}</span></header><dl>{developmentFacts.map(([label, value, state]) => <div key={label}><dt>{label}</dt><dd className={`is-${state}`}>{value}</dd></div>)}</dl></section><section className="command-panel document-center"><header><h2>{copy.documents}</h2><span>{commandDocuments.length}</span></header><div className="document-list">{commandDocuments.map((document) => <button type="button" key={document[0]} className={selectedDocument[0] === document[0] ? 'is-active' : ''} onClick={() => setSelectedDocument(document)}><strong>{document[0]}</strong><span>{document[2]}</span></button>)}</div><article><strong>{selectedDocument[0]}</strong><p>{selectedDocument[1]}</p><span>{copy.exists} · {selectedDocument[2]}</span><button type="button" disabled>{copy.view} · local file</button></article></section></div>
      <section className="command-section"><header><div><span>PRIORITY QUEUE</span><h2>{copy.nextTasks}</h2></div><strong>{data.open.length}</strong></header><div className="command-task-table"><div className="command-task-head"><span>#</span><span>{copy.project}</span><span>{copy.task}</span><span>{copy.priority}</span><span>{copy.taskStatus}</span><span>{copy.revenue}</span><span>{copy.blocking}</span><span>{copy.assigned}</span></div>{data.open.slice(0, 10).map((task, index) => { const localized = localizeTaskContent(task, language, t); return <article key={task.id}><strong>{index + 1}</strong><span>{localized.project || localized.category}</span><b>{localized.title}</b><span>{t(localized.priority === 'critical' ? 'taskCritical' : 'taskImportant')}</span><span>{t(`taskStatus_${localized.status}`)}</span><span>{localized.revenueImpact ? `$${Number(localized.revenueImpact).toLocaleString()}` : '—'}</span><span>{localized.isBlocking ? copy.yes : copy.no}</span><span>{localized.assignee || '—'}</span></article> })}</div></section>
      <div className="command-two-column"><section className="command-panel known-issues"><header><h2>{copy.issues}</h2><span>{knownCommandIssues.length}</span></header>{['critical', 'high', 'medium', 'low'].map((severity) => <div key={severity}><h3>{copy[severity]}</h3>{knownCommandIssues.filter((issue) => issue[0] === severity).map((issue) => <article key={issue[1]}><strong>{issue[1]}</strong><p>{issue[2]}</p></article>)}</div>)}</section><div className="command-side-stack"><section className="command-panel ai-summary"><header><h2>{copy.ai}</h2><span>{copy.notConnected}</span></header><dl><div><dt>{copy.activeAgents}</dt><dd>0</dd></div><div><dt>{copy.idleAgents}</dt><dd>0</dd></div><div><dt>{copy.failedAgents}</dt><dd>0</dd></div><div><dt>{copy.queued}</dt><dd>0</dd></div><div><dt>{copy.lastAgent}</dt><dd>{copy.unavailable}</dd></div><div><dt>{copy.assignedProject}</dt><dd>{copy.unavailable}</dd></div></dl></section><IdeaCapture copy={copy} /></div></div>
    </>}
  </section>
}
