import { useEffect, useMemo, useState } from 'react'
import { useAuth } from '../../context/AuthContext'
import { supabase } from '../../services/supabaseClient'
import { isOwner, ROLES } from '../../services/authorization'
import './UsersPermissions.css'
export default function UsersPermissions() {
  const { profile } = useAuth(); const [users, setUsers] = useState([]); const [query, setQuery] = useState(''); const [role, setRole] = useState('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  async function loadUsers() { setLoading(true); const result = await supabase.from('users').select('auth_user_id,email,role,business_id,active,created_at').order('created_at', { ascending: false }); if (result.error) setError(result.error.message); else setUsers(result.data || []); setLoading(false) }
  useEffect(() => { void loadUsers() }, [])
  const filtered = useMemo(() => users.filter((user) => (!query || user.email.toLowerCase().includes(query.toLowerCase())) && (role === 'all' || user.role === role)), [users, query, role]); const activeOwners = users.filter((user) => isOwner(user) && user.active).length
  async function updateUser(user, changes) { if (user.auth_user_id === profile?.auth_user_id && (changes.role && changes.role !== ROLES.OWNER || changes.active === false)) return; if (isOwner(user) && user.active && changes.active === false && activeOwners <= 1) return; const result = await supabase.from('users').update(changes).eq('auth_user_id', user.auth_user_id); if (result.error) setError(result.error.message); else void loadUsers() }
  return <section className="users-permissions" dir="rtl"><header><div><span>GrowthPilot OS</span><h1>Users & Permissions</h1></div><div><button type="button" onClick={() => window.open('https://supabase.com/dashboard/project/_/auth/users', '_blank', 'noopener,noreferrer')}>Add User</button><button type="button" onClick={() => void loadUsers()}>Refresh Users</button></div></header><p>Create or invite the user in Supabase, then return here and refresh.</p><div className="users-permissions__filters"><input placeholder="Search email" value={query} onChange={(event) => setQuery(event.target.value)} /><select value={role} onChange={(event) => setRole(event.target.value)}><option value="all">All roles</option><option value={ROLES.OWNER}>Owner</option><option value={ROLES.ADMIN}>Admin</option><option value={ROLES.SALES}>Sales</option><option value={ROLES.CLIENT}>Client</option><option value={ROLES.DEMO}>Demo</option><option value={ROLES.EMPLOYEE}>Employee (legacy)</option></select></div>{loading ? <p>Loading users…</p> : error ? <p>{error}</p> : <table><thead><tr><th>Email</th><th>Role</th><th>Active</th><th>Created</th><th>Access</th></tr></thead><tbody>{filtered.map((user) => <tr key={user.auth_user_id}><td>{user.email}</td><td><select value={user.role} disabled={user.auth_user_id === profile?.auth_user_id} onChange={(event) => void updateUser(user, { role: event.target.value })}><option value={ROLES.OWNER}>Owner</option><option value={ROLES.ADMIN}>Admin</option><option value={ROLES.SALES}>Sales</option><option value={ROLES.CLIENT}>Client</option><option value={ROLES.DEMO}>Demo</option><option value={ROLES.EMPLOYEE}>Employee (legacy)</option></select></td><td>{user.active ? 'Active' : 'Inactive'}</td><td>{new Date(user.created_at).toLocaleString()}</td><td><button type="button" disabled={user.auth_user_id === profile?.auth_user_id || (isOwner(user) && user.active && activeOwners <= 1)} onClick={() => void updateUser(user, { active: !user.active })}>{user.active ? 'Deactivate' : 'Activate'}</button></td></tr>)}</tbody></table>}</section>
}
