// Generates business-type-aware, SEO-ready website content without AI or external data.
import { getRealWebsiteTemplate } from './realWebsiteTemplates'

const common = {
  en: { nav: ['About', 'Services', 'Process', 'Reviews', 'Contact'], about: 'Built around your needs', services: 'Services designed to deliver', why: 'Why clients choose us', process: 'A clear, simple process', highlights: 'Service you can count on', reviews: 'What clients say', faq: 'Frequently asked questions', finalTitle: 'Ready to take the next step?', contact: 'Let’s start a conversation', primary: 'Get a free consultation', secondary: 'Explore our services', call: 'Call now', form: 'Send inquiry', name: 'Your name', message: 'How can we help?', map: 'View on Google Maps', response: 'Fast response', local: 'Local expertise', quality: 'Quality focused', stepTitles: ['Tell us what you need', 'Receive a clear plan', 'Move forward with confidence'], fallback: 'Professional service, clear communication, and dependable results for every customer.', faqFallback: [['How quickly can we get started?', 'Contact us today and we will confirm the next available time.'], ['Do you provide a clear quote?', 'Yes. We explain the scope and next steps before work begins.'], ['Which areas do you serve?', 'We serve local customers and nearby communities.']] },
  he: { nav: ['אודות', 'שירותים', 'תהליך', 'המלצות', 'יצירת קשר'], about: 'שירות שנבנה סביב הצרכים שלכם', services: 'שירותים שמביאים תוצאות', why: 'למה לקוחות בוחרים בנו', process: 'תהליך פשוט וברור', highlights: 'שירות שאפשר לסמוך עליו', reviews: 'מה הלקוחות אומרים', faq: 'שאלות נפוצות', finalTitle: 'מוכנים להתקדם?', contact: 'בואו נתחיל בשיחה', primary: 'לקביעת ייעוץ', secondary: 'לצפייה בשירותים', call: 'התקשרו עכשיו', form: 'שליחת פנייה', name: 'השם שלכם', message: 'איך נוכל לעזור?', map: 'פתיחה ב-Google Maps', response: 'מענה מהיר', local: 'מומחיות מקומית', quality: 'מחויבות לאיכות', stepTitles: ['ספרו לנו מה אתם צריכים', 'קבלו תוכנית ברורה', 'מתקדמים בביטחון'], fallback: 'שירות מקצועי, תקשורת ברורה ותוצאות אמינות לכל לקוח.', faqFallback: [['מתי אפשר להתחיל?', 'צרו קשר ונאשר את המועד הקרוב ביותר.'], ['האם מקבלים הצעת מחיר ברורה?', 'כן. אנו מסבירים את היקף העבודה והשלבים לפני שמתחילים.'], ['באילו אזורים אתם עובדים?', 'אנו משרתים לקוחות באזור המקומי ובסביבה.']] },
  ar: { nav: ['من نحن', 'الخدمات', 'الخطوات', 'الآراء', 'اتصل بنا'], about: 'خدمة مبنية حول احتياجاتك', services: 'خدمات مصممة لتحقيق النتائج', why: 'لماذا يختارنا العملاء', process: 'خطوات واضحة وبسيطة', highlights: 'خدمة يمكنك الاعتماد عليها', reviews: 'آراء العملاء', faq: 'الأسئلة الشائعة', finalTitle: 'هل أنت مستعد للخطوة التالية؟', contact: 'لنبدأ محادثة', primary: 'احجز استشارة', secondary: 'استكشف الخدمات', call: 'اتصل الآن', form: 'إرسال الطلب', name: 'الاسم', message: 'كيف يمكننا مساعدتك؟', map: 'فتح Google Maps', response: 'استجابة سريعة', local: 'خبرة محلية', quality: 'التزام بالجودة', stepTitles: ['أخبرنا بما تحتاجه', 'احصل على خطة واضحة', 'تقدم بثقة'], fallback: 'خدمة مهنية وتواصل واضح ونتائج موثوقة لكل عميل.', faqFallback: [['متى يمكننا البدء؟', 'تواصل معنا اليوم وسنؤكد أقرب موعد متاح.'], ['هل تقدمون عرضًا واضحًا؟', 'نعم، نشرح نطاق العمل والخطوات قبل البدء.'], ['ما المناطق التي تخدمونها؟', 'نخدم العملاء المحليين والمناطق القريبة.']] },
  ru: { nav: ['О нас', 'Услуги', 'Процесс', 'Отзывы', 'Контакты'], about: 'Сервис, построенный вокруг ваших задач', services: 'Услуги, ориентированные на результат', why: 'Почему клиенты выбирают нас', process: 'Понятный и простой процесс', highlights: 'Сервис, которому можно доверять', reviews: 'Что говорят клиенты', faq: 'Частые вопросы', finalTitle: 'Готовы сделать следующий шаг?', contact: 'Давайте обсудим вашу задачу', primary: 'Получить консультацию', secondary: 'Посмотреть услуги', call: 'Позвонить', form: 'Отправить запрос', name: 'Ваше имя', message: 'Чем мы можем помочь?', map: 'Открыть Google Maps', response: 'Быстрый ответ', local: 'Местная экспертиза', quality: 'Фокус на качестве', stepTitles: ['Расскажите о задаче', 'Получите понятный план', 'Двигайтесь вперёд уверенно'], fallback: 'Профессиональный сервис, ясная коммуникация и надёжный результат для каждого клиента.', faqFallback: [['Как быстро можно начать?', 'Свяжитесь с нами, и мы подтвердим ближайшее доступное время.'], ['Вы предоставляете понятную смету?', 'Да. До начала мы объясняем объём и следующие шаги.'], ['Какие районы вы обслуживаете?', 'Мы работаем с местными клиентами и ближайшими районами.']] },
}

// Shared customer-facing labels that keep every generated site in its selected language.
const customerLabels = {
  en: { email: 'Email', areaEyebrow: 'Service areas', areaTitle: 'Local service, close to you', areaText: 'Serving customers locally with clear availability and a fast response.', nearby: 'Nearby communities', surrounding: 'Surrounding areas' },
  he: { email: 'דוא״ל', areaEyebrow: 'אזורי שירות', areaTitle: 'שירות מקומי, קרוב אליכם', areaText: 'מעניקים שירות באזור המקומי עם זמינות ברורה ומענה מהיר.', nearby: 'יישובים סמוכים', surrounding: 'האזור והסביבה' },
  ar: { email: 'البريد الإلكتروني', areaEyebrow: 'مناطق الخدمة', areaTitle: 'خدمة محلية قريبة منك', areaText: 'نخدم العملاء محليًا مع توافر واضح واستجابة سريعة.', nearby: 'المناطق القريبة', surrounding: 'المنطقة والمحيط' },
  ru: { email: 'Эл. почта', areaEyebrow: 'Районы обслуживания', areaTitle: 'Местный сервис рядом с вами', areaText: 'Работаем с местными клиентами, быстро отвечаем и заранее подтверждаем доступность.', nearby: 'Ближайшие районы', surrounding: 'Город и окрестности' },
}

Object.keys(common).forEach((language) => Object.assign(common[language], customerLabels[language]))

const industries = {
  mechanic: { keys: ['mechanic', 'garage', 'auto repair', 'מוסך', 'מכונאי', 'ميكانيكي', 'автосервис'], en: ['Diagnostics', 'Scheduled maintenance', 'Brake and engine repair'], he: ['אבחון תקלות', 'טיפולים תקופתיים', 'תיקוני בלמים ומנוע'], ar: ['فحص الأعطال', 'الصيانة الدورية', 'إصلاح المحرك والفرامل'], ru: ['Диагностика', 'Плановое обслуживание', 'Ремонт двигателя и тормозов'], angle: ['reliable repairs', 'תיקונים אמינים', 'إصلاحات موثوقة', 'надёжный ремонт'] },
  dentist: { keys: ['dentist', 'dental', 'רופא שיניים', 'שיניים', 'طبيب أسنان', 'стоматолог'], en: ['Preventive care', 'Restorative dentistry', 'Comfortable appointments'], he: ['טיפולי מניעה', 'שיקום הפה', 'טיפול נעים ומקצועי'], ar: ['العناية الوقائية', 'ترميم الأسنان', 'مواعيد مريحة'], ru: ['Профилактика', 'Восстановление зубов', 'Комфортный приём'], angle: ['comfortable dental care', 'טיפול שיניים מקצועי ונעים', 'عناية أسنان مريحة', 'комфортная стоматология'] },
  lawyer: { keys: ['lawyer', 'attorney', 'law firm', 'עורך דין', 'محامي', 'юрист', 'адвокат'], en: ['Confidential consultation', 'Case strategy', 'Professional representation'], he: ['ייעוץ דיסקרטי', 'בניית אסטרטגיה לתיק', 'ייצוג מקצועי'], ar: ['استشارة سرية', 'استراتيجية القضية', 'تمثيل مهني'], ru: ['Конфиденциальная консультация', 'Стратегия дела', 'Профессиональное представительство'], angle: ['trusted legal guidance', 'ליווי משפטי שאפשר לסמוך עליו', 'إرشاد قانوني موثوق', 'надёжная юридическая помощь'] },
  restaurant: { keys: ['restaurant', 'cafe', 'מסעדה', 'בית קפה', 'مطعم', 'ресторан'], en: ['Seasonal menu', 'Welcoming atmosphere', 'Reservations and events'], he: ['תפריט עונתי', 'אווירה מזמינה', 'הזמנות ואירועים'], ar: ['قائمة موسمية', 'أجواء ترحيبية', 'حجوزات ومناسبات'], ru: ['Сезонное меню', 'Уютная атмосфера', 'Бронирование и события'], angle: ['memorable food and atmosphere', 'טעמים ואווירה שלא שוכחים', 'طعام وأجواء لا تُنسى', 'незабываемая кухня и атмосфера'] },
  beauty: { keys: ['beauty', 'salon', 'cosmetic', 'יופי', 'קוסמט', 'صالون', 'красот'], en: ['Signature treatments', 'Personal consultations', 'Results-focused care'], he: ['טיפולי דגל', 'ייעוץ אישי', 'טיפוח ממוקד תוצאות'], ar: ['علاجات مميزة', 'استشارات شخصية', 'عناية تركز على النتائج'], ru: ['Фирменные процедуры', 'Личные консультации', 'Уход с видимым результатом'], angle: ['confident, natural results', 'תוצאות טבעיות שמעניקות ביטחון', 'نتائج طبيعية تمنح الثقة', 'естественный результат и уверенность'] },
  plumber: { keys: ['plumber', 'plumbing', 'אינסטלטור', 'سباك', 'сантехник'], en: ['Emergency response', 'Leak detection', 'Repairs and installations'], he: ['שירות חירום', 'איתור נזילות', 'תיקונים והתקנות'], ar: ['استجابة طارئة', 'كشف التسربات', 'إصلاحات وتركيبات'], ru: ['Аварийный выезд', 'Поиск протечек', 'Ремонт и установка'], angle: ['fast local plumbing help', 'שירות אינסטלציה מקומי ומהיר', 'خدمة سباكة محلية سريعة', 'быстрая местная помощь сантехника'] },
}

function industryFor(type = '') { const value = type.toLowerCase(); return Object.values(industries).find((item) => item.keys.some((key) => value.includes(key))) }
function initials(name) { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((word) => word[0]).join('').toUpperCase() || 'B' }

export function generateRealWebsite(customer) {
  const language = common[customer.language] ? customer.language : 'en'; const text = common[language]; const languageIndex = ['en', 'he', 'ar', 'ru'].indexOf(language)
  const name = customer.businessName?.trim() || ({ en: 'Your Business', he: 'העסק שלכם', ar: 'نشاطك التجاري', ru: 'Ваш бизнес' }[language])
  const industry = industryFor(customer.businessType); const customServices = String(customer.mainServices || '').split(/[,\n]/).map((item) => item.trim()).filter(Boolean)
  const services = (customServices.length ? customServices : industry?.[language] || [text.local, text.quality, text.response]).slice(0, 6)
  const angle = industry?.angle?.[languageIndex] || text.fallback
  const location = customer.city ? ` ${customer.city}` : ''
  const headline = language === 'he' ? `${name}: ${angle}${location ? ` ב${location.trim()}` : ''}` : language === 'ar' ? `${name}: ${angle}${location ? ` في${location}` : ''}` : `${name}: ${angle}${location ? ` in${location}` : ''}`
  const description = customer.shortDescription?.trim() || text.fallback
  const template = getRealWebsiteTemplate(customer.preferredTemplate)
  return { schemaVersion: 2, direction: ['he', 'ar'].includes(language) ? 'rtl' : 'ltr', template,
    seo: { title: `${name} | ${customer.businessType || text.local}`, metaDescription: description.slice(0, 155), openGraph: { title: headline, description, image: customer.heroImageUrl || '' }, localBusinessSchema: { '@context': 'https://schema.org', '@type': 'LocalBusiness', name, telephone: customer.phone || '', email: customer.email || '', address: customer.address || '', url: customer.currentWebsite || '' } },
    sections: { header: { name, initials: initials(name), nav: text.nav }, hero: { eyebrow: customer.businessType || text.local, headline, description, primary: text.primary, secondary: text.secondary, image: customer.heroImageUrl || '', trust: [text.response, text.local, text.quality] }, about: { title: text.about, text: description }, services: { title: text.services, items: services.map((title, index) => ({ title, text: `${title} — ${description}`, number: String(index + 1).padStart(2, '0') })) }, why: { title: text.why, items: [text.response, text.local, text.quality] }, process: { title: text.process, items: text.stepTitles.map((title, index) => ({ title, text: index === 0 ? text.message : index === 1 ? text.fallback : text.primary })) }, highlights: { title: text.highlights, items: [{ value: '3+', label: text.quality }, { value: '100%', label: text.local }, { value: '24h', label: text.response }] }, reviews: { title: text.reviews, items: [text.fallback, description, text.fallback] }, faq: { title: text.faq, items: text.faqFallback }, finalCta: { title: text.finalTitle, text: description, button: text.primary }, contact: { title: text.contact, call: text.call, form: text.form, name: text.name, message: text.message, maps: text.map }, footer: { text: `© ${new Date().getFullYear()} ${name}`, nav: text.nav }, gallery: String(customer.galleryImageUrls || '').split(/[\n,]/).map((url) => url.trim()).filter(Boolean).slice(0, 6) },
  }
}

export function isReadyToPublish(customer, site) { return Boolean(customer.businessName?.trim() && (customer.phone?.trim() || customer.email?.trim()) && site.sections.services.items.length >= 3 && site.sections.hero.headline?.trim() && site.sections.contact) }
