create table if not exists public.user_management_audit (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.users(auth_user_id) on delete set null,
  target_user_id uuid references public.users(auth_user_id) on delete set null,
  action text not null check (action in ('user_invited', 'user_updated', 'user_disabled', 'password_reset_requested')),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.user_management_audit
  drop constraint if exists user_management_audit_action_check;
alter table public.user_management_audit
  add constraint user_management_audit_action_check
  check (action in ('user_invited', 'user_updated', 'user_disabled', 'password_reset_requested'));

create index if not exists user_management_audit_actor_idx
  on public.user_management_audit(actor_user_id, created_at desc);
create index if not exists user_management_audit_target_idx
  on public.user_management_audit(target_user_id, created_at desc);

alter table public.user_management_audit enable row level security;

create or replace function public.provision_invited_user(
  actor_id uuid,
  target_id uuid,
  target_name text,
  target_email text,
  target_role text,
  target_business_ids text[],
  audit_details jsonb
)
returns void
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
begin
  insert into public.users(auth_user_id, name, email, role, active, business_id)
  values (
    target_id,
    target_name,
    target_email,
    target_role,
    true,
    target_business_ids[1]
  )
  on conflict (auth_user_id) do update
  set
    name = excluded.name,
    email = excluded.email,
    role = excluded.role,
    active = true,
    business_id = excluded.business_id;

  delete from public.business_memberships
  where user_id = target_id;

  insert into public.business_memberships(user_id, business_id)
  select target_id, assigned.business_id
  from unnest(coalesce(target_business_ids, array[]::text[])) as assigned(business_id);

  insert into public.user_management_audit(actor_user_id, target_user_id, action, details)
  values (actor_id, target_id, 'user_invited', coalesce(audit_details, '{}'::jsonb));
end;
$$;

create or replace function public.apply_user_management_update(
  actor_id uuid,
  target_id uuid,
  next_name text,
  next_role text,
  next_active boolean,
  next_business_ids text[],
  change_name boolean,
  change_role boolean,
  change_active boolean,
  change_businesses boolean,
  audit_action text,
  audit_details jsonb
)
returns void
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
declare
  current_profile public.users%rowtype;
  resulting_role text;
  resulting_active boolean;
  active_owner_count bigint;
begin
  perform pg_advisory_xact_lock(hashtextextended('business-os-active-owner-transition', 0));

  select *
  into current_profile
  from public.users
  where auth_user_id = target_id
  for update;

  if not found then
    raise exception 'User was not found.';
  end if;

  resulting_role := case when change_role then next_role else current_profile.role end;
  resulting_active := case when change_active then next_active else current_profile.active end;

  if current_profile.role = 'owner'
    and current_profile.active
    and (resulting_role <> 'owner' or not resulting_active)
  then
    select count(*)
    into active_owner_count
    from public.users
    where role = 'owner' and active = true;

    if active_owner_count <= 1 then
      raise exception 'The last active owner cannot be changed or disabled.';
    end if;
  end if;

  if change_businesses then
    delete from public.business_memberships
    where user_id = target_id;

    insert into public.business_memberships(user_id, business_id)
    select target_id, assigned.business_id
    from unnest(coalesce(next_business_ids, array[]::text[])) as assigned(business_id);
  end if;

  update public.users
  set
    name = case when change_name then next_name else name end,
    role = resulting_role,
    active = resulting_active,
    business_id = case when change_businesses then next_business_ids[1] else business_id end
  where auth_user_id = target_id;

  insert into public.user_management_audit(actor_user_id, target_user_id, action, details)
  values (actor_id, target_id, audit_action, coalesce(audit_details, '{}'::jsonb));
end;
$$;

drop policy if exists "authorized managers can read user audit" on public.user_management_audit;
create policy "authorized managers can read user audit"
on public.user_management_audit for select
to authenticated
using (
  private.current_user_role() = 'owner'
  or private.current_user_can_manage_user(target_user_id)
);

revoke all on public.user_management_audit from anon, authenticated;
grant select on public.user_management_audit to authenticated;

revoke all on function public.provision_invited_user(uuid, uuid, text, text, text, text[], jsonb) from public, anon, authenticated;
grant execute on function public.provision_invited_user(uuid, uuid, text, text, text, text[], jsonb) to service_role;
revoke all on function public.apply_user_management_update(uuid, uuid, text, text, boolean, text[], boolean, boolean, boolean, boolean, text, jsonb) from public, anon, authenticated;
grant execute on function public.apply_user_management_update(uuid, uuid, text, text, boolean, text[], boolean, boolean, boolean, boolean, text, jsonb) to service_role;
