// Bilingual conversion content shared by every Demo Website section.
const TEXT = {
  en: { local: 'Trusted local service', hero: 'Local expertise. Personal service. Results you can trust.', heroText: (name) => `A simpler way to connect with ${name}—clear communication and professional local help.`, call: 'Call Now', whatsapp: 'WhatsApp', directions: 'Directions', servicesNav: 'Services', contactNav: 'Contact', explore: 'Explore Services', aboutEye: 'Local. Responsive. Professional.', about: (place) => `Service built around customers in ${place}`, aboutText: (name) => `${name} makes it easy to ask questions, understand the next step, and get dependable local help.`, highlight: 'Clear communication · Convenient contact · Local knowledge', services: 'Services', servicesEye: 'How we can help', why: 'Why customers choose us', whyEye: 'Why choose us', easy: ['Easy to Reach', 'Call or message directly without unnecessary friction.'], knowledge: ['Local Knowledge', 'Convenient service for local customers and nearby areas.'], steps: ['Clear Next Steps', 'Helpful communication so you know what to expect.'], reputation: 'Google reputation', trusted: 'Trusted by local customers', reviewFallback: 'View the latest customer feedback on Google', viewReviews: 'View reviews on Google', area: 'Service area', areaTitle: (place) => `Proudly serving ${place}`, areaText: 'Send your location and the team will confirm availability.', nearby: 'Nearby neighborhoods', surrounding: 'Surrounding communities', faqEye: 'Good to know', faq: 'Frequently asked questions', contactEye: 'Ready when you are', contact: (name) => `Contact ${name}`, contactText: 'Tell us what you need and choose the easiest way to connect.', name: 'Your name', help: 'How can we help?', send: 'Send via WhatsApp', unavailable: 'Call the business directly to get started.', phone: 'Phone', visit: 'Visit us', online: 'Online', proof: 'LOCAL BUSINESS', proofText: 'Fast contact. Clear next steps. Professional local service.', clickCall: 'Click to call', ready: 'WhatsApp ready', easyDirections: 'Easy directions', rights: 'All rights reserved.' },
  he: { local: 'שירות מקומי שאפשר לסמוך עליו', hero: 'מקצועיות מקומית. יחס אישי. שירות שנותן ביטחון.', heroText: (name) => `הדרך הפשוטה ליצור קשר עם ${name}—תקשורת ברורה ושירות מקומי מקצועי.`, call: 'התקשרו עכשיו', whatsapp: 'WhatsApp', directions: 'ניווט', servicesNav: 'שירותים', contactNav: 'יצירת קשר', explore: 'לצפייה בשירותים', aboutEye: 'מקומי. זמין. מקצועי.', about: (place) => `שירות שנבנה עבור לקוחות ב${place}`, aboutText: (name) => `${name} מאפשר לכם לשאול, להבין את השלב הבא ולקבל שירות מקומי אמין.`, highlight: 'תקשורת ברורה · יצירת קשר נוחה · היכרות מקומית', services: 'השירותים שלנו', servicesEye: 'איך נוכל לעזור', why: 'למה לקוחות בוחרים בנו', whyEye: 'למה אנחנו', easy: ['קל ליצור קשר', 'שיחה או הודעה ישירה, בלי תהליך מסובך.'], knowledge: ['היכרות מקומית', 'שירות נוח ללקוחות באזור ובסביבה.'], steps: ['שלבים ברורים', 'תקשורת מועילה כדי שתדעו למה לצפות.'], reputation: 'המוניטין שלנו ב-Google', trusted: 'לקוחות מקומיים סומכים עלינו', reviewFallback: 'לצפייה במשוב העדכני של לקוחות ב-Google', viewReviews: 'לצפייה בביקורות ב-Google', area: 'אזורי שירות', areaTitle: (place) => `משרתים בגאווה את ${place}`, areaText: 'שלחו את המיקום שלכם והצוות יאשר זמינות.', nearby: 'שכונות סמוכות', surrounding: 'יישובים באזור', faqEye: 'טוב לדעת', faq: 'שאלות נפוצות', contactEye: 'מוכנים כשאתם מוכנים', contact: (name) => `יצירת קשר עם ${name}`, contactText: 'ספרו לנו מה אתם צריכים ובחרו את הדרך הנוחה ליצור קשר.', name: 'השם שלכם', help: 'איך נוכל לעזור?', send: 'שליחה ב-WhatsApp', unavailable: 'התקשרו ישירות לעסק כדי להתחיל.', phone: 'טלפון', visit: 'כתובת', online: 'אתר', proof: 'עסק מקומי', proofText: 'יצירת קשר מהירה. שלבים ברורים. שירות מקומי מקצועי.', clickCall: 'שיחה בלחיצה', ready: 'WhatsApp זמין', easyDirections: 'ניווט קל', rights: 'כל הזכויות שמורות.' },
}

const INDUSTRIES = {
  dentist: { match: ['dent', 'שיניים'], en: ['Dental care', 'A healthier smile starts with care you can trust.', ['Preventive Care', 'Restorative Treatment', 'Smile Consultations']], he: ['רפואת שיניים', 'חיוך בריא מתחיל בטיפול שאפשר לסמוך עליו.', ['טיפולי מניעה', 'טיפולים משקמים', 'ייעוץ לחיוך בריא']] },
  beauty: { match: ['beauty', 'salon', 'cosmetic', 'קוסמט', 'יופי'], en: ['Beauty & wellness', 'Feel confident with treatments designed around you.', ['Personal Consultation', 'Signature Treatments', 'Ongoing Care']], he: ['יופי וטיפוח', 'להרגיש בטוחים עם טיפולים שמותאמים אליכם.', ['ייעוץ אישי', 'טיפולי דגל', 'טיפוח מתמשך']] },
  restaurant: { match: ['restaurant', 'cafe', 'מסעד', 'קפה'], en: ['Local dining', 'Great food, warm hospitality, and a place worth returning to.', ['Freshly Prepared', 'Welcoming Atmosphere', 'Reservations & Events']], he: ['מסעדה מקומית', 'טעמים מעולים, אירוח חם ומקום שכיף לחזור אליו.', ['מנות טריות', 'אווירה מזמינה', 'הזמנות ואירועים']] },
  legal: { match: ['law', 'legal', 'עורך דין'], en: ['Legal services', 'Clear legal guidance when the next decision matters.', ['Confidential Consultation', 'Case Strategy', 'Professional Representation']], he: ['שירותים משפטיים', 'ליווי משפטי ברור כשההחלטה הבאה חשובה.', ['ייעוץ דיסקרטי', 'אסטרטגיה לתיק', 'ייצוג מקצועי']] },
  mechanic: { match: ['garage', 'mechanic', 'auto', 'מוסך'], en: ['Automotive service', 'Reliable service that gets you safely back on the road.', ['Vehicle Diagnostics', 'Repairs & Maintenance', 'Fast Local Support']], he: ['שירותי רכב', 'שירות אמין שמחזיר אתכם לכביש בבטחה.', ['אבחון רכב', 'תיקונים ותחזוקה', 'שירות מקומי מהיר']] },
  plumber: { match: ['plumb', 'אינסטלט'], en: ['Local plumbing', 'Fast, dependable plumbing help when you need it.', ['Leak Detection', 'Repairs & Installations', 'Urgent Assistance']], he: ['אינסטלציה מקומית', 'עזרה מהירה ואמינה בדיוק כשצריך.', ['איתור נזילות', 'תיקונים והתקנות', 'סיוע דחוף']] },
}

function languageOf(business) { return business.language === 'he' ? 'he' : 'en' }
function profileFor(business) { const lang = languageOf(business); const value = `${business.type || ''} ${business.name || ''}`.toLowerCase(); const found = Object.values(INDUSTRIES).find((item) => item.match.some((term) => value.includes(term))); return found?.[lang] || [TEXT[lang].local, TEXT[lang].hero, lang === 'he' ? ['שירות אישי', 'מומחיות מקצועית', 'תמיכה אמינה'] : ['Personal Service', 'Professional Expertise', 'Reliable Support']] }
function faq(business) { return languageOf(business) === 'he' ? [['איך מתחילים?', 'התקשרו או שלחו הודעת WhatsApp והצוות יסביר את השלב הבא.'], ['באילו אזורים אתם נותנים שירות?', 'שלחו את המיקום שלכם כדי לאשר כיסוי.'], ['אפשר לקבל מידע נוסף?', 'כן, אפשר ליצור קשר ישירות דרך האפשרויות למטה.']] : [['How do I get started?', 'Call or send a WhatsApp message and the team will explain the next step.'], ['Which areas do you serve?', 'Send your location to confirm coverage.'], ['Can I request more information?', 'Yes—use the contact options below.']]
}

export const websiteSections = {
  hero: { id: 'hero', type: 'hero', createContent: (b) => { const t = TEXT[languageOf(b)], p = profileFor(b); return { eyebrow: `${p[0]} · ${b.location}`, title: b.name, headline: p[1], text: t.heroText(b.name), primaryAction: { label: b.phone ? t.call : t.contactNav, href: b.phone ? `tel:${b.phone}` : '#contact' }, secondaryAction: { label: t.explore, href: '#services' }, rating: b.rating, reviewsCount: b.reviewsCount, ui: t } } },
  about: { id: 'about', type: 'content', createContent: (b) => { const t = TEXT[languageOf(b)]; return { eyebrow: t.aboutEye, heading: t.about(b.location), text: t.aboutText(b.name), highlight: t.highlight } } },
  services: { id: 'services', type: 'features', createContent: (b) => { const t = TEXT[languageOf(b)], p = profileFor(b); return { eyebrow: t.servicesEye, heading: t.services, intro: t.aboutText(b.name), items: p[2].map((title, i) => ({ icon: String(i + 1).padStart(2, '0'), title, text: languageOf(b) === 'he' ? 'שירות מקצועי עם תקשורת ברורה ותשומת לב לפרטים.' : 'Professional service with clear communication and attention to detail.' })) } } },
  'why-us': { id: 'why-us', type: 'features', createContent: (b) => { const t = TEXT[languageOf(b)]; return { eyebrow: t.whyEye, heading: t.why, intro: t.highlight, items: [t.easy, t.knowledge, t.steps].map(([title, text]) => ({ icon: '✓', title, text })) } } },
  testimonials: { id: 'testimonials', type: 'testimonials', createContent: (b) => { const t = TEXT[languageOf(b)]; return { eyebrow: t.reputation, heading: t.trusted, rating: b.rating, mapsUrl: b.mapsUrl, summary: b.rating ? `${b.rating.toFixed(1)} / 5${b.reviewsCount ? ` · ${b.reviewsCount}` : ''}` : t.reviewFallback, viewReviews: t.viewReviews } } },
  'service-areas': { id: 'service-areas', type: 'service-areas', createContent: (b) => { const t = TEXT[languageOf(b)]; return { eyebrow: t.area, heading: t.areaTitle(b.location), text: t.areaText, areas: [b.location, t.nearby, t.surrounding] } } },
  faq: { id: 'faq', type: 'faq', createContent: (b) => { const t = TEXT[languageOf(b)]; return { eyebrow: t.faqEye, heading: t.faq, items: faq(b) } } },
  contact: { id: 'contact', type: 'contact', createContent: (b) => { const t = TEXT[languageOf(b)]; return { heading: t.contact(b.name), eyebrow: t.contactEye, text: t.contactText, phone: b.phone, address: b.address, website: b.website, mapsUrl: b.mapsUrl, businessName: b.name, ui: t } } },
  footer: { id: 'footer', type: 'footer', createContent: (b) => { const t = TEXT[languageOf(b)]; return { businessName: b.name, tagline: t.areaTitle(b.location), rights: t.rights } } },
}
export function getWebsiteSection(id) { return websiteSections[id] || null }
export default websiteSections
